CREATE TABLE elem_voc (
    orders varchar(5),
    vocab varchar(300),
    def	varchar(300),
    pos	varchar(300)
);

INSERT INTO elem_voc VALUES ('0', 'a', '一個', '冠詞');
INSERT INTO elem_voc VALUES ('1', 'about', '1. 大約；2. 關於...', '介系詞');
INSERT INTO elem_voc VALUES ('2', 'actor', '男演員', '名詞');
INSERT INTO elem_voc VALUES ('3', 'actress', '女演員', '名詞');
INSERT INTO elem_voc VALUES ('4', 'after', '在...之後', '介系詞');
INSERT INTO elem_voc VALUES ('5', 'afternoon', '下午', '名詞');
INSERT INTO elem_voc VALUES ('6', 'again', '再一次、又一次', '副詞');
INSERT INTO elem_voc VALUES ('7', 'airplane', '飛機 (= plane)', '名詞');
INSERT INTO elem_voc VALUES ('8', 'airport', '機場', '名詞');
INSERT INTO elem_voc VALUES ('9', 'all', '全部的', '限定詞');
INSERT INTO elem_voc VALUES ('10', 'always', '總是、永遠', '副詞');
INSERT INTO elem_voc VALUES ('11', 'an', '一個', '冠詞');
INSERT INTO elem_voc VALUES ('12', 'and', '和', '連接詞');
INSERT INTO elem_voc VALUES ('13', 'angry', '生氣的', '形容詞');
INSERT INTO elem_voc VALUES ('14', 'animal', '動物', '名詞');
INSERT INTO elem_voc VALUES ('15', 'answer', '回答', '動詞');
INSERT INTO elem_voc VALUES ('16', 'apple', '蘋果', '名詞');
INSERT INTO elem_voc VALUES ('17', 'April', '四月', '名詞');
INSERT INTO elem_voc VALUES ('18', 'arm', '手臂', '名詞');
INSERT INTO elem_voc VALUES ('19', 'art', '美術、藝術', '名詞');
INSERT INTO elem_voc VALUES ('20', 'ask', '問', '動詞');
INSERT INTO elem_voc VALUES ('21', 'at', '在(某處)、在(時刻)', '介系詞');
INSERT INTO elem_voc VALUES ('22', 'August', '八月', '名詞');
INSERT INTO elem_voc VALUES ('23', 'aunt', '阿姨、姑姑、伯母、舅媽', '名詞');
INSERT INTO elem_voc VALUES ('24', 'away', '離開', '副詞');
INSERT INTO elem_voc VALUES ('25', 'a', '一個', '冠詞');
INSERT INTO elem_voc VALUES ('26', 'about', '1. 大約；2. 關於...', '介系詞');
INSERT INTO elem_voc VALUES ('27', 'actor', '男演員', '名詞');
INSERT INTO elem_voc VALUES ('28', 'actress', '女演員', '名詞');
INSERT INTO elem_voc VALUES ('29', 'after', '在...之後', '介系詞');
INSERT INTO elem_voc VALUES ('30', 'afternoon', '下午', '名詞');
INSERT INTO elem_voc VALUES ('31', 'again', '再一次、又一次', '副詞');
INSERT INTO elem_voc VALUES ('32', 'airplane', '飛機 (= plane)', '名詞');
INSERT INTO elem_voc VALUES ('33', 'airport', '機場', '名詞');
INSERT INTO elem_voc VALUES ('34', 'all', '全部的', '限定詞');
INSERT INTO elem_voc VALUES ('35', 'always', '總是、永遠', '副詞');
INSERT INTO elem_voc VALUES ('36', 'an', '一個', '冠詞');
INSERT INTO elem_voc VALUES ('37', 'and', '和', '連接詞');
INSERT INTO elem_voc VALUES ('38', 'angry', '生氣的', '形容詞');
INSERT INTO elem_voc VALUES ('39', 'animal', '動物', '名詞');
INSERT INTO elem_voc VALUES ('40', 'answer', '回答', '動詞');
INSERT INTO elem_voc VALUES ('41', 'apple', '蘋果', '名詞');
INSERT INTO elem_voc VALUES ('42', 'April', '四月', '名詞');
INSERT INTO elem_voc VALUES ('43', 'arm', '手臂', '名詞');
INSERT INTO elem_voc VALUES ('44', 'art', '美術、藝術', '名詞');
INSERT INTO elem_voc VALUES ('45', 'ask', '問', '動詞');
INSERT INTO elem_voc VALUES ('46', 'at', '在(某處)、在(時刻)', '介系詞');
INSERT INTO elem_voc VALUES ('47', 'August', '八月', '名詞');
INSERT INTO elem_voc VALUES ('48', 'aunt', '阿姨、姑姑、伯母、舅媽', '名詞');
INSERT INTO elem_voc VALUES ('49', 'away', '離開', '副詞');
INSERT INTO elem_voc VALUES ('50', 'baby', '嬰兒', '名詞');
INSERT INTO elem_voc VALUES ('51', 'back', '背', '名詞');
INSERT INTO elem_voc VALUES ('52', 'back', '向後、回原處', '副詞');
INSERT INTO elem_voc VALUES ('53', 'bad', '不好的、壞的', '形容詞');
INSERT INTO elem_voc VALUES ('54', 'bag', '袋子', '名詞');
INSERT INTO elem_voc VALUES ('55', 'ball', '球', '名詞');
INSERT INTO elem_voc VALUES ('56', 'banana', '香蕉', '名詞');
INSERT INTO elem_voc VALUES ('57', 'bank', '銀行', '名詞');
INSERT INTO elem_voc VALUES ('58', 'baseball', '棒球', '名詞');
INSERT INTO elem_voc VALUES ('59', 'basketball', '籃球', '名詞');
INSERT INTO elem_voc VALUES ('60', 'bathroom', '浴室', '名詞');
INSERT INTO elem_voc VALUES ('61', 'be', '是 (is, am, are)', '助動詞');
INSERT INTO elem_voc VALUES ('62', 'beach', '海灘', '名詞');
INSERT INTO elem_voc VALUES ('63', 'bear', '熊', '名詞');
INSERT INTO elem_voc VALUES ('64', 'beautiful', '美麗的、漂亮的', '形容詞');
INSERT INTO elem_voc VALUES ('65', 'because', '因為', '連接詞');
INSERT INTO elem_voc VALUES ('66', 'bed', '床', '名詞');
INSERT INTO elem_voc VALUES ('67', 'bedroom', '臥房', '名詞');
INSERT INTO elem_voc VALUES ('68', 'bee', '蜜蜂', '名詞');
INSERT INTO elem_voc VALUES ('69', 'beef', '牛肉', '名詞');
INSERT INTO elem_voc VALUES ('70', 'before', '在...之前', '介系詞, 連接詞');
INSERT INTO elem_voc VALUES ('71', 'behind', '在...後面', '介系詞');
INSERT INTO elem_voc VALUES ('72', 'bicycle', '腳踏車 (= bike)', '名詞');
INSERT INTO elem_voc VALUES ('73', 'big', '大的', '形容詞');
INSERT INTO elem_voc VALUES ('74', 'bike', '腳踏車 (= bicycle)', '名詞');
INSERT INTO elem_voc VALUES ('75', 'bird', '鳥', '名詞');
INSERT INTO elem_voc VALUES ('76', 'birthday', '生日', '名詞');
INSERT INTO elem_voc VALUES ('77', 'bite', '咬', '動詞');
INSERT INTO elem_voc VALUES ('78', 'black', '黑色的', '形容詞');
INSERT INTO elem_voc VALUES ('79', 'blackboard', '黑板', '名詞');
INSERT INTO elem_voc VALUES ('80', 'blue', '藍色的', '形容詞');
INSERT INTO elem_voc VALUES ('81', 'boat', '船', '名詞');
INSERT INTO elem_voc VALUES ('82', 'book', '書、書本', '名詞');
INSERT INTO elem_voc VALUES ('83', 'bookstore', '書店', '名詞');
INSERT INTO elem_voc VALUES ('84', 'bored', '覺得無聊的', '形容詞');
INSERT INTO elem_voc VALUES ('85', 'boring', '令人無聊的', '形容詞');
INSERT INTO elem_voc VALUES ('86', 'both', '兩個都', '限定詞');
INSERT INTO elem_voc VALUES ('87', 'bottle', '瓶子', '名詞');
INSERT INTO elem_voc VALUES ('88', 'box', '箱子', '名詞');
INSERT INTO elem_voc VALUES ('89', 'boy', '男孩', '名詞');
INSERT INTO elem_voc VALUES ('90', 'bread', '麵包', '名詞');
INSERT INTO elem_voc VALUES ('91', 'breakfast', '早餐', '名詞');
INSERT INTO elem_voc VALUES ('92', 'brother', '哥哥、弟弟', '名詞');
INSERT INTO elem_voc VALUES ('93', 'brown', '咖啡色的', '形容詞');
INSERT INTO elem_voc VALUES ('94', 'brush', '用刷子刷', '動詞');
INSERT INTO elem_voc VALUES ('95', 'bus', '公車', '名詞');
INSERT INTO elem_voc VALUES ('96', 'bus stop', '公車站', '名詞');
INSERT INTO elem_voc VALUES ('97', 'busy', '忙碌的', '形容詞');
INSERT INTO elem_voc VALUES ('98', 'but', '但是', '連接詞');
INSERT INTO elem_voc VALUES ('99', 'butterfly', '蝴蝶', '名詞');
INSERT INTO elem_voc VALUES ('100', 'buy', '買', '動詞');
INSERT INTO elem_voc VALUES ('101', 'by', '在...旁邊', '介系詞');
INSERT INTO elem_voc VALUES ('102', 'bye', '再見 (= goodbye)', '感嘆詞');
INSERT INTO elem_voc VALUES ('103', 'cake', '蛋糕', '名詞');
INSERT INTO elem_voc VALUES ('104', 'call', '打電話給...', '動詞');
INSERT INTO elem_voc VALUES ('105', 'can', '可以', '助動詞');
INSERT INTO elem_voc VALUES ('106', 'can', '罐子', '名詞');
INSERT INTO elem_voc VALUES ('107', 'candy', '糖果', '名詞');
INSERT INTO elem_voc VALUES ('108', 'cap', '棒球帽', '名詞');
INSERT INTO elem_voc VALUES ('109', 'car', '車子', '名詞');
INSERT INTO elem_voc VALUES ('110', 'card', '卡片', '名詞');
INSERT INTO elem_voc VALUES ('111', 'cat', '貓', '名詞');
INSERT INTO elem_voc VALUES ('112', 'cellphone', '手機', '名詞');
INSERT INTO elem_voc VALUES ('113', 'chair', '椅子', '名詞');
INSERT INTO elem_voc VALUES ('114', 'chicken', '雞', '名詞');
INSERT INTO elem_voc VALUES ('115', 'chicken', '雞肉', '名詞');
INSERT INTO elem_voc VALUES ('116', 'Chinese', '中文', '名詞');
INSERT INTO elem_voc VALUES ('117', 'chocolate', '巧克力', '名詞');
INSERT INTO elem_voc VALUES ('118', 'chopsticks', '筷子', '名詞');
INSERT INTO elem_voc VALUES ('119', 'class', '課；班級', '名詞');
INSERT INTO elem_voc VALUES ('120', 'classroom', '教室', '名詞');
INSERT INTO elem_voc VALUES ('121', 'clean', '乾淨的', '形容詞');
INSERT INTO elem_voc VALUES ('122', 'clean', '清理', '動詞');
INSERT INTO elem_voc VALUES ('123', 'climb', '爬、攀爬', '動詞');
INSERT INTO elem_voc VALUES ('124', 'clock', '時鐘', '名詞');
INSERT INTO elem_voc VALUES ('125', 'close', '關', '動詞');
INSERT INTO elem_voc VALUES ('126', 'clothes', '衣服', '名詞');
INSERT INTO elem_voc VALUES ('127', 'cloudy', '多雲的', '形容詞');
INSERT INTO elem_voc VALUES ('128', 'coat', '外套', '名詞');
INSERT INTO elem_voc VALUES ('129', 'coffee', '咖啡', '名詞');
INSERT INTO elem_voc VALUES ('130', 'coke', '可樂', '名詞');
INSERT INTO elem_voc VALUES ('131', 'cold', '寒冷的', '形容詞');
INSERT INTO elem_voc VALUES ('132', 'cold', '感冒', '名詞');
INSERT INTO elem_voc VALUES ('133', 'color', '顏色', '名詞');
INSERT INTO elem_voc VALUES ('134', 'come', '來', '動詞');
INSERT INTO elem_voc VALUES ('135', 'computer', '電腦', '名詞');
INSERT INTO elem_voc VALUES ('136', 'cook', '廚師', '名詞');
INSERT INTO elem_voc VALUES ('137', 'cook', '做飯', '動詞');
INSERT INTO elem_voc VALUES ('138', 'cookies', '餅乾', '名詞');
INSERT INTO elem_voc VALUES ('139', 'cool', '涼爽的', '形容詞');
INSERT INTO elem_voc VALUES ('140', 'cool', '清涼的', '形容詞');
INSERT INTO elem_voc VALUES ('141', 'cousin', '堂兄（弟、姊、妹）', '名詞');
INSERT INTO elem_voc VALUES ('142', 'cow', '乳牛', '名詞');
INSERT INTO elem_voc VALUES ('143', 'cry', '哭、哭泣', '動詞');
INSERT INTO elem_voc VALUES ('144', 'cup', '杯子', '名詞');
INSERT INTO elem_voc VALUES ('145', 'cute', '可愛的', '形容詞');
INSERT INTO elem_voc VALUES ('146', 'dad', '爸爸 (= father; daddy)', '名詞');
INSERT INTO elem_voc VALUES ('147', 'daddy', '爸爸 (= father; dad)', '名詞');
INSERT INTO elem_voc VALUES ('148', 'dance', '跳舞', '動詞');
INSERT INTO elem_voc VALUES ('149', 'daughter', '女兒', '名詞');
INSERT INTO elem_voc VALUES ('150', 'day', '天', '名詞');
INSERT INTO elem_voc VALUES ('151', 'December', '十二月', '名詞');
INSERT INTO elem_voc VALUES ('152', 'department store', '百貨公司', '名詞');
INSERT INTO elem_voc VALUES ('153', 'desk', '桌子', '名詞');
INSERT INTO elem_voc VALUES ('154', 'different', '不一樣的', '形容詞');
INSERT INTO elem_voc VALUES ('155', 'dining room', '(家裡的)餐廳', '名詞');
INSERT INTO elem_voc VALUES ('156', 'dinner', '晚餐', '名詞');
INSERT INTO elem_voc VALUES ('157', 'dirty', '髒的', '形容詞');
INSERT INTO elem_voc VALUES ('158', 'dish', '碟子、盤子', '名詞');
INSERT INTO elem_voc VALUES ('159', 'do', '助動詞', '助動詞');
INSERT INTO elem_voc VALUES ('160', 'do', '做', '動詞');
INSERT INTO elem_voc VALUES ('161', 'doctor', '醫生', '名詞');
INSERT INTO elem_voc VALUES ('162', 'dog', '狗', '名詞');
INSERT INTO elem_voc VALUES ('163', 'doll', '玩偶', '名詞');
INSERT INTO elem_voc VALUES ('164', 'dollar', '元', '名詞');
INSERT INTO elem_voc VALUES ('165', 'door', '門', '名詞');
INSERT INTO elem_voc VALUES ('166', 'draw', '畫、描畫', '動詞');
INSERT INTO elem_voc VALUES ('167', 'dream', '夢', '名詞');
INSERT INTO elem_voc VALUES ('168', 'dress', '洋裝', '名詞');
INSERT INTO elem_voc VALUES ('169', 'drink', '喝', '動詞');
INSERT INTO elem_voc VALUES ('170', 'drive', '開車', '動詞');
INSERT INTO elem_voc VALUES ('171', 'driver', '司機、駕駛員', '名詞');
INSERT INTO elem_voc VALUES ('172', 'drum', '鼓', '名詞');
INSERT INTO elem_voc VALUES ('173', 'duck', '鴨子', '名詞');
INSERT INTO elem_voc VALUES ('174', 'duck', '鴨肉', '名詞');
INSERT INTO elem_voc VALUES ('175', 'dumpling', '水餃', '名詞');
INSERT INTO elem_voc VALUES ('176', 'ear', '耳朵', '名詞');
INSERT INTO elem_voc VALUES ('177', 'early', '早到（的）', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('178', 'easy', '簡單的', '形容詞');
INSERT INTO elem_voc VALUES ('179', 'eat', '吃', '動詞');
INSERT INTO elem_voc VALUES ('180', 'egg', '蛋', '名詞');
INSERT INTO elem_voc VALUES ('181', 'eight', '八', '數字');
INSERT INTO elem_voc VALUES ('182', 'eighteen', '十八', '數字');
INSERT INTO elem_voc VALUES ('183', 'eighty', '八十', '數字');
INSERT INTO elem_voc VALUES ('184', 'elephant', '大象', '名詞');
INSERT INTO elem_voc VALUES ('185', 'eleven', '十一', '數字');
INSERT INTO elem_voc VALUES ('186', 'email', '電子郵件', '名詞');
INSERT INTO elem_voc VALUES ('187', 'English', '英文', '名詞');
INSERT INTO elem_voc VALUES ('188', 'enjoy', '享受、喜歡', '動詞');
INSERT INTO elem_voc VALUES ('189', 'eraser', '橡皮擦', '名詞');
INSERT INTO elem_voc VALUES ('190', 'evening', '傍晚', '名詞');
INSERT INTO elem_voc VALUES ('191', 'every', '每一個', '限定詞');
INSERT INTO elem_voc VALUES ('192', 'excited', '覺得興奮的', '形容詞');
INSERT INTO elem_voc VALUES ('193', 'exciting', '令人興奮的', '形容詞');
INSERT INTO elem_voc VALUES ('194', 'excuse me', '不好意思、對不起', '感嘆詞');
INSERT INTO elem_voc VALUES ('195', 'eye', '眼睛', '名詞');
INSERT INTO elem_voc VALUES ('196', 'face', '臉', '名詞');
INSERT INTO elem_voc VALUES ('197', 'fall', '秋天', '名詞');
INSERT INTO elem_voc VALUES ('198', 'fall', '掉落', '動詞');
INSERT INTO elem_voc VALUES ('199', 'family', '家庭、家人', '名詞');
INSERT INTO elem_voc VALUES ('200', 'fan', '電扇', '名詞');
INSERT INTO elem_voc VALUES ('201', 'farmer', '農夫', '名詞');
INSERT INTO elem_voc VALUES ('202', 'fast', '快速的（地）', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('203', 'father', '爸爸 (= dad; daddy)', '名詞');
INSERT INTO elem_voc VALUES ('204', 'favorite', '最喜歡的', '形容詞');
INSERT INTO elem_voc VALUES ('205', 'February', '二月', '名詞');
INSERT INTO elem_voc VALUES ('206', 'feel', '感受、感覺', '動詞');
INSERT INTO elem_voc VALUES ('207', 'feet', '腳 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('208', 'fifteen', '十五', '數字');
INSERT INTO elem_voc VALUES ('209', 'fifty', '五十', '數字');
INSERT INTO elem_voc VALUES ('210', 'find', '找', '動詞');
INSERT INTO elem_voc VALUES ('211', 'fine', '很好的、很不錯的', '形容詞');
INSERT INTO elem_voc VALUES ('212', 'fire station', '消防站', '名詞');
INSERT INTO elem_voc VALUES ('213', 'first', '第一', '數字');
INSERT INTO elem_voc VALUES ('214', 'fish', '魚', '名詞');
INSERT INTO elem_voc VALUES ('215', 'fish', '魚肉', '名詞');
INSERT INTO elem_voc VALUES ('216', 'fish', '釣魚', '動詞');
INSERT INTO elem_voc VALUES ('217', 'five', '五', '數字');
INSERT INTO elem_voc VALUES ('218', 'floor', '地板', '名詞');
INSERT INTO elem_voc VALUES ('219', 'flower', '花', '名詞');
INSERT INTO elem_voc VALUES ('220', 'fly', '飛、飛行', '動詞');
INSERT INTO elem_voc VALUES ('221', 'food', '食物', '名詞');
INSERT INTO elem_voc VALUES ('222', 'foot', '腳', '名詞');
INSERT INTO elem_voc VALUES ('223', 'football', '足球 (UK; 英式英語)', '名詞');
INSERT INTO elem_voc VALUES ('224', 'for', '給、為了(某人、物)', '介系詞');
INSERT INTO elem_voc VALUES ('225', 'fork', '叉子', '名詞');
INSERT INTO elem_voc VALUES ('226', 'forty', '四十', '數字');
INSERT INTO elem_voc VALUES ('227', 'four', '四', '數字');
INSERT INTO elem_voc VALUES ('228', 'fourteen', '十四', '數字');
INSERT INTO elem_voc VALUES ('229', 'free', '免費的', '形容詞');
INSERT INTO elem_voc VALUES ('230', 'French fries', '薯條', '名詞');
INSERT INTO elem_voc VALUES ('231', 'Friday', '星期五', '名詞');
INSERT INTO elem_voc VALUES ('232', 'fridge', '電冰箱 (= refrigerator)', '名詞');
INSERT INTO elem_voc VALUES ('233', 'friend', '朋友', '名詞');
INSERT INTO elem_voc VALUES ('234', 'frog', '青蛙', '名詞');
INSERT INTO elem_voc VALUES ('235', 'from', '從(某處)/(某時刻)/(某人)', '介系詞');
INSERT INTO elem_voc VALUES ('236', 'fruit', '水果', '名詞');
INSERT INTO elem_voc VALUES ('237', 'full', '飽的', '形容詞');
INSERT INTO elem_voc VALUES ('238', 'fun', '有趣的', '形容詞');
INSERT INTO elem_voc VALUES ('239', 'fun', '樂趣', '名詞');
INSERT INTO elem_voc VALUES ('240', 'game', '遊戲、比賽', '名詞');
INSERT INTO elem_voc VALUES ('241', 'garden', '院子、花園', '名詞');
INSERT INTO elem_voc VALUES ('242', 'get', '得到、收到', '動詞');
INSERT INTO elem_voc VALUES ('243', 'gift', '禮物', '名詞');
INSERT INTO elem_voc VALUES ('244', 'girl', '女孩', '名詞');
INSERT INTO elem_voc VALUES ('245', 'give', '給', '動詞');
INSERT INTO elem_voc VALUES ('246', 'glass', '玻璃杯', '名詞');
INSERT INTO elem_voc VALUES ('247', 'glasses', '眼鏡', '名詞');
INSERT INTO elem_voc VALUES ('248', 'glue', '膠水', '名詞');
INSERT INTO elem_voc VALUES ('249', 'go', '去、走', '動詞');
INSERT INTO elem_voc VALUES ('250', 'good', '好的', '形容詞');
INSERT INTO elem_voc VALUES ('251', 'goodbye', '再見 (= bye)', '感嘆詞');
INSERT INTO elem_voc VALUES ('252', 'grandfather', '外公、爺爺 (= grandpa)', '名詞');
INSERT INTO elem_voc VALUES ('253', 'grandma', '外婆、奶奶 (= grandmother)', '名詞');
INSERT INTO elem_voc VALUES ('254', 'grandmother', '外婆、奶奶 (= grandma)', '名詞');
INSERT INTO elem_voc VALUES ('255', 'grandpa', '外公、爺爺 (= grandfather)', '名詞');
INSERT INTO elem_voc VALUES ('256', 'grape', '葡萄', '名詞');
INSERT INTO elem_voc VALUES ('257', 'gray', '灰色的', '形容詞');
INSERT INTO elem_voc VALUES ('258', 'great', '很棒的', '形容詞');
INSERT INTO elem_voc VALUES ('259', 'green', '綠色的', '形容詞');
INSERT INTO elem_voc VALUES ('260', 'grow', '成長、長大', '動詞');
INSERT INTO elem_voc VALUES ('261', 'hair', '頭髮', '名詞');
INSERT INTO elem_voc VALUES ('262', 'hamburger', '漢堡', '名詞');
INSERT INTO elem_voc VALUES ('263', 'hand', '手', '名詞');
INSERT INTO elem_voc VALUES ('264', 'happy', '開心的、高興的', '形容詞');
INSERT INTO elem_voc VALUES ('265', 'hard', '困難的', '形容詞');
INSERT INTO elem_voc VALUES ('266', 'hat', '帽子', '名詞');
INSERT INTO elem_voc VALUES ('267', 'have', '助動詞', '助動詞');
INSERT INTO elem_voc VALUES ('268', 'have', '有', '動詞');
INSERT INTO elem_voc VALUES ('269', 'he', '他', '代名詞');
INSERT INTO elem_voc VALUES ('270', 'head', '頭', '名詞');
INSERT INTO elem_voc VALUES ('271', 'headache', '頭痛', '名詞');
INSERT INTO elem_voc VALUES ('272', 'heavy', '重的 (人)', '形容詞');
INSERT INTO elem_voc VALUES ('273', 'heavy', '重的 (物品)', '形容詞');
INSERT INTO elem_voc VALUES ('274', 'hello', '哈囉', '感嘆詞');
INSERT INTO elem_voc VALUES ('275', 'help', '幫助', '動詞');
INSERT INTO elem_voc VALUES ('276', 'her', '她的', '限定詞');
INSERT INTO elem_voc VALUES ('277', 'her', '她', '代名詞');
INSERT INTO elem_voc VALUES ('278', 'here', '這裡', '副詞');
INSERT INTO elem_voc VALUES ('279', 'hi', '嗨', '感嘆詞');
INSERT INTO elem_voc VALUES ('280', 'high', '高的', '形容詞');
INSERT INTO elem_voc VALUES ('281', 'hike', '健行', '動詞');
INSERT INTO elem_voc VALUES ('282', 'him', '他(受詞)', '代名詞');
INSERT INTO elem_voc VALUES ('283', 'hippo', '河馬', '名詞');
INSERT INTO elem_voc VALUES ('284', 'his', '他的', '限定詞');
INSERT INTO elem_voc VALUES ('285', 'hit', '打、碰撞', '動詞');
INSERT INTO elem_voc VALUES ('286', 'home', '家庭', '名詞');
INSERT INTO elem_voc VALUES ('287', 'homework', '回家作業', '名詞');
INSERT INTO elem_voc VALUES ('288', 'hope', '希望', '動詞');
INSERT INTO elem_voc VALUES ('289', 'horse', '馬', '名詞');
INSERT INTO elem_voc VALUES ('290', 'hospital', '醫院', '名詞');
INSERT INTO elem_voc VALUES ('291', 'hot', '熱的', '形容詞');
INSERT INTO elem_voc VALUES ('292', 'hot', '燙的', '形容詞');
INSERT INTO elem_voc VALUES ('293', 'house', '房子', '名詞');
INSERT INTO elem_voc VALUES ('294', 'how', '如何...', '副詞');
INSERT INTO elem_voc VALUES ('295', 'hundred', '一百', '數字');
INSERT INTO elem_voc VALUES ('296', 'hungry', '餓的', '形容詞');
INSERT INTO elem_voc VALUES ('297', 'hurry', '趕快、急忙', '動詞');
INSERT INTO elem_voc VALUES ('298', 'hurt', '受傷', '動詞');
INSERT INTO elem_voc VALUES ('299', 'I', '我', '代名詞');
INSERT INTO elem_voc VALUES ('300', 'ice cream', '冰淇淋', '名詞');
INSERT INTO elem_voc VALUES ('301', 'in', '在...裡面、在某短時間裡', '介系詞');
INSERT INTO elem_voc VALUES ('302', 'in front of', '在...前面', '介系詞');
INSERT INTO elem_voc VALUES ('303', 'inside', '在...裡面、向...裡面', '介系詞');
INSERT INTO elem_voc VALUES ('304', 'interesting', '有趣的', '形容詞');
INSERT INTO elem_voc VALUES ('305', 'it', '它、牠', '代名詞');
INSERT INTO elem_voc VALUES ('306', 'its', '它的、牠的', '限定詞');
INSERT INTO elem_voc VALUES ('307', 'jacket', '夾克、外套', '名詞');
INSERT INTO elem_voc VALUES ('308', 'January', '一月', '名詞');
INSERT INTO elem_voc VALUES ('309', 'job', '工作、職業', '名詞');
INSERT INTO elem_voc VALUES ('310', 'juice', '果汁', '名詞');
INSERT INTO elem_voc VALUES ('311', 'July', '七月', '名詞');
INSERT INTO elem_voc VALUES ('312', 'jump', '跳', '動詞');
INSERT INTO elem_voc VALUES ('313', 'June', '六月', '名詞');
INSERT INTO elem_voc VALUES ('314', 'lake', '湖', '名詞');
INSERT INTO elem_voc VALUES ('315', 'lamp', '燈', '名詞');
INSERT INTO elem_voc VALUES ('316', 'last', '最後的', '限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('317', 'late', '晚到（的）', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('318', 'laugh', '笑', '動詞');
INSERT INTO elem_voc VALUES ('319', 'lazy', '懶惰的', '形容詞');
INSERT INTO elem_voc VALUES ('320', 'left', '左邊(的)', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('321', 'leg', '腿', '名詞');
INSERT INTO elem_voc VALUES ('322', 'lemon', '檸檬', '名詞');
INSERT INTO elem_voc VALUES ('323', 's', '讓我們...', '動詞');
INSERT INTO elem_voc VALUES ('324', 'library', '圖書館', '名詞');
INSERT INTO elem_voc VALUES ('325', 'light', '輕的', '形容詞');
INSERT INTO elem_voc VALUES ('326', 'like', '喜歡', '動詞');
INSERT INTO elem_voc VALUES ('327', 'lion', '獅子', '名詞');
INSERT INTO elem_voc VALUES ('328', 'listen', '聽', '動詞');
INSERT INTO elem_voc VALUES ('329', 'live', '住', '動詞');
INSERT INTO elem_voc VALUES ('330', 'living room', '客廳', '名詞');
INSERT INTO elem_voc VALUES ('331', 'long', '長的', '形容詞');
INSERT INTO elem_voc VALUES ('332', 'look', '看、看起來', '動詞');
INSERT INTO elem_voc VALUES ('333', 'love', '愛、喜愛', '動詞');
INSERT INTO elem_voc VALUES ('334', 'lunch', '午餐', '名詞');
INSERT INTO elem_voc VALUES ('335', 'lake', '湖', '名詞');
INSERT INTO elem_voc VALUES ('336', 'lamp', '燈', '名詞');
INSERT INTO elem_voc VALUES ('337', 'last', '最後的', '限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('338', 'late', '晚到（的）', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('339', 'laugh', '笑', '動詞');
INSERT INTO elem_voc VALUES ('340', 'lazy', '懶惰的', '形容詞');
INSERT INTO elem_voc VALUES ('341', 'left', '左邊(的)', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('342', 'leg', '腿', '名詞');
INSERT INTO elem_voc VALUES ('343', 'lemon', '檸檬', '名詞');
INSERT INTO elem_voc VALUES ('344', 's', '讓我們...', '動詞');
INSERT INTO elem_voc VALUES ('345', 'library', '圖書館', '名詞');
INSERT INTO elem_voc VALUES ('346', 'light', '輕的', '形容詞');
INSERT INTO elem_voc VALUES ('347', 'like', '喜歡', '動詞');
INSERT INTO elem_voc VALUES ('348', 'lion', '獅子', '名詞');
INSERT INTO elem_voc VALUES ('349', 'listen', '聽', '動詞');
INSERT INTO elem_voc VALUES ('350', 'live', '住', '動詞');
INSERT INTO elem_voc VALUES ('351', 'living room', '客廳', '名詞');
INSERT INTO elem_voc VALUES ('352', 'long', '長的', '形容詞');
INSERT INTO elem_voc VALUES ('353', 'look', '看、看起來', '動詞');
INSERT INTO elem_voc VALUES ('354', 'love', '愛、喜愛', '動詞');
INSERT INTO elem_voc VALUES ('355', 'lunch', '午餐', '名詞');
INSERT INTO elem_voc VALUES ('356', 'mad', '生氣的、氣憤的', '形容詞');
INSERT INTO elem_voc VALUES ('357', 'mail', '信', '名詞');
INSERT INTO elem_voc VALUES ('358', 'mailman', '郵差', '名詞');
INSERT INTO elem_voc VALUES ('359', 'make', '做、製造', '動詞');
INSERT INTO elem_voc VALUES ('360', 'man', '男人', '名詞');
INSERT INTO elem_voc VALUES ('361', 'many', '許多(例如many flowers)', '限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('362', 'March', '三月', '名詞');
INSERT INTO elem_voc VALUES ('363', 'marker', '麥克筆', '名詞');
INSERT INTO elem_voc VALUES ('364', 'market', '市場', '名詞');
INSERT INTO elem_voc VALUES ('365', 'math', '數學', '名詞');
INSERT INTO elem_voc VALUES ('366', 'May', '五月', '名詞');
INSERT INTO elem_voc VALUES ('367', 'maybe', '也許', '副詞');
INSERT INTO elem_voc VALUES ('368', 'me', '我(受詞)', '代名詞');
INSERT INTO elem_voc VALUES ('369', 'meal', '餐', '名詞');
INSERT INTO elem_voc VALUES ('370', 'meet', '遇見、會面', '動詞');
INSERT INTO elem_voc VALUES ('371', 'men', '男人 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('372', 'mice', '老鼠 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('373', 'milk', '牛奶', '名詞');
INSERT INTO elem_voc VALUES ('374', 'miss', '想念', '動詞');
INSERT INTO elem_voc VALUES ('375', 'Miss', '小姐', '');
INSERT INTO elem_voc VALUES ('376', 'mom', '媽媽 (= mother; mommy)', '名詞');
INSERT INTO elem_voc VALUES ('377', 'mommy', '媽媽 (= mother; mom)', '名詞');
INSERT INTO elem_voc VALUES ('378', 'Monday', '星期一', '名詞');
INSERT INTO elem_voc VALUES ('379', 'money', '錢', '名詞');
INSERT INTO elem_voc VALUES ('380', 'monkey', '猴子', '名詞');
INSERT INTO elem_voc VALUES ('381', 'month', '月', '名詞');
INSERT INTO elem_voc VALUES ('382', 'moon', '月亮', '名詞');
INSERT INTO elem_voc VALUES ('383', 'mop', '用拖把拖地', '動詞');
INSERT INTO elem_voc VALUES ('384', 'more', '更多、較多', '限定詞, 副詞');
INSERT INTO elem_voc VALUES ('385', 'morning', '早上', '名詞');
INSERT INTO elem_voc VALUES ('386', 'mother', '媽媽 (= mom; mommy)', '名詞');
INSERT INTO elem_voc VALUES ('387', 'motorcycle', '摩托車', '名詞');
INSERT INTO elem_voc VALUES ('388', 'mountain', '山', '名詞');
INSERT INTO elem_voc VALUES ('389', 'mouse', '老鼠', '名詞');
INSERT INTO elem_voc VALUES ('390', 'mouth', '嘴巴', '名詞');
INSERT INTO elem_voc VALUES ('391', 'movie', '電影', '名詞');
INSERT INTO elem_voc VALUES ('392', 'movie theater', '電影院', '名詞');
INSERT INTO elem_voc VALUES ('393', 'Mr.', '先生', '');
INSERT INTO elem_voc VALUES ('394', 'Mrs.', '太太', '');
INSERT INTO elem_voc VALUES ('395', 'MRT', '捷運', '名詞');
INSERT INTO elem_voc VALUES ('396', 'much', '許多(例如much water)', '限定詞,副詞');
INSERT INTO elem_voc VALUES ('397', 'museum', '博物館', '名詞');
INSERT INTO elem_voc VALUES ('398', 'music', '音樂', '名詞');
INSERT INTO elem_voc VALUES ('399', 'my', '我的', '限定詞');
INSERT INTO elem_voc VALUES ('400', 'name', '名字', '名詞');
INSERT INTO elem_voc VALUES ('401', 'near', '靠近、接近', '介系詞');
INSERT INTO elem_voc VALUES ('402', 'need', '需要', '動詞');
INSERT INTO elem_voc VALUES ('403', 'never', '不曾', '副詞');
INSERT INTO elem_voc VALUES ('404', 'new', '新的', '形容詞');
INSERT INTO elem_voc VALUES ('405', 'next to', '在...旁邊', '介系詞');
INSERT INTO elem_voc VALUES ('406', 'nice', '令人愉快的、宜人的', '形容詞');
INSERT INTO elem_voc VALUES ('407', 'night', '晚上', '名詞');
INSERT INTO elem_voc VALUES ('408', 'nine', '九', '數字');
INSERT INTO elem_voc VALUES ('409', 'nineteen', '十九', '數字');
INSERT INTO elem_voc VALUES ('410', 'ninety', '九十', '數字');
INSERT INTO elem_voc VALUES ('411', 'no', '不', '副詞');
INSERT INTO elem_voc VALUES ('412', 'noodles', '麵', '名詞');
INSERT INTO elem_voc VALUES ('413', 'nose', '鼻子', '名詞');
INSERT INTO elem_voc VALUES ('414', 'not', '不、沒有', '副詞');
INSERT INTO elem_voc VALUES ('415', 'nothing', '什麼都沒有', '代名詞');
INSERT INTO elem_voc VALUES ('416', 'November', '十一月', '名詞');
INSERT INTO elem_voc VALUES ('417', 'now', '現在', '副詞');
INSERT INTO elem_voc VALUES ('418', 'number', '數字', '名詞');
INSERT INTO elem_voc VALUES ('419', 'nurse', '護士', '名詞');
INSERT INTO elem_voc VALUES ('420', 'clock', '...點鐘', '副詞');
INSERT INTO elem_voc VALUES ('421', 'October', '十月', '名詞');
INSERT INTO elem_voc VALUES ('422', 'of', '...的', '介系詞');
INSERT INTO elem_voc VALUES ('423', 'off', '離開、從...去掉', '介系詞');
INSERT INTO elem_voc VALUES ('424', 'office', '辦公室', '名詞');
INSERT INTO elem_voc VALUES ('425', 'OK', '好的', '形容詞');
INSERT INTO elem_voc VALUES ('426', 'OK', '沒事', '副詞');
INSERT INTO elem_voc VALUES ('427', 'old', '1. 年紀、年齡；2. 老的', '形容詞');
INSERT INTO elem_voc VALUES ('428', 'on', '在...上面；在(某一天)', '介系詞');
INSERT INTO elem_voc VALUES ('429', 'one', '一', '數字');
INSERT INTO elem_voc VALUES ('430', 'only', '僅有的', '形容詞');
INSERT INTO elem_voc VALUES ('431', 'only', '唯一地', '副詞');
INSERT INTO elem_voc VALUES ('432', 'open', '開', '動詞');
INSERT INTO elem_voc VALUES ('433', 'orange', '橘色的', '形容詞');
INSERT INTO elem_voc VALUES ('434', 'orange', '橘子', '名詞');
INSERT INTO elem_voc VALUES ('435', 'other', '其他的', '形容詞, 代名詞, 限定詞');
INSERT INTO elem_voc VALUES ('436', 'our', '我們的', '限定詞');
INSERT INTO elem_voc VALUES ('437', 'out', '向外地', '介系詞');
INSERT INTO elem_voc VALUES ('438', 'outside', '在...外面、向...外面', '介系詞');
INSERT INTO elem_voc VALUES ('439', 'over', '在...上方', '介系詞');
INSERT INTO elem_voc VALUES ('440', 'paint', '用顏料畫、刷油漆', '動詞');
INSERT INTO elem_voc VALUES ('441', 'pair', '一雙、一對', '名詞');
INSERT INTO elem_voc VALUES ('442', 'panda', '大貓熊', '名詞');
INSERT INTO elem_voc VALUES ('443', 'pants', '長褲', '名詞');
INSERT INTO elem_voc VALUES ('444', 'paper', '紙張', '名詞');
INSERT INTO elem_voc VALUES ('445', 'parent', '父母親', '名詞');
INSERT INTO elem_voc VALUES ('446', 'park', '公園', '名詞');
INSERT INTO elem_voc VALUES ('447', 'party', '派對', '名詞');
INSERT INTO elem_voc VALUES ('448', 'PE', '體育（課）', '名詞');
INSERT INTO elem_voc VALUES ('449', 'peach', '桃子', '名詞');
INSERT INTO elem_voc VALUES ('450', 'pen', '筆、鋼筆', '名詞');
INSERT INTO elem_voc VALUES ('451', 'pencil', '鉛筆', '名詞');
INSERT INTO elem_voc VALUES ('452', 'people', '人 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('453', 'person', '人', '名詞');
INSERT INTO elem_voc VALUES ('454', 'pet', '寵物', '名詞');
INSERT INTO elem_voc VALUES ('455', 'photo', '照片', '名詞');
INSERT INTO elem_voc VALUES ('456', 'piano', '鋼琴', '名詞');
INSERT INTO elem_voc VALUES ('457', 'pick up', '撿起、接（人）、接（電話）', '動詞');
INSERT INTO elem_voc VALUES ('458', 'picture', '圖片、照片', '名詞');
INSERT INTO elem_voc VALUES ('459', 'pie', '派', '名詞');
INSERT INTO elem_voc VALUES ('460', 'pig', '豬', '名詞');
INSERT INTO elem_voc VALUES ('461', 'pink', '粉紅色的', '形容詞');
INSERT INTO elem_voc VALUES ('462', 'pizza', '披薩', '名詞');
INSERT INTO elem_voc VALUES ('463', 'plane', '飛機 (= airplane)', '名詞');
INSERT INTO elem_voc VALUES ('464', 'play', '玩', '動詞');
INSERT INTO elem_voc VALUES ('465', 'please', '請', '感嘆詞');
INSERT INTO elem_voc VALUES ('466', 'pocket', '口袋', '名詞');
INSERT INTO elem_voc VALUES ('467', 'police officer', '警察', '名詞');
INSERT INTO elem_voc VALUES ('468', 'police station', '警察局', '名詞');
INSERT INTO elem_voc VALUES ('469', 'pork', '豬肉', '名詞');
INSERT INTO elem_voc VALUES ('470', 'post office', '郵局', '名詞');
INSERT INTO elem_voc VALUES ('471', 'pretty', '漂亮的', '形容詞');
INSERT INTO elem_voc VALUES ('472', 'pumpkin', '南瓜', '名詞');
INSERT INTO elem_voc VALUES ('473', 'purple', '紫色的', '形容詞');
INSERT INTO elem_voc VALUES ('474', 'put', '放', '動詞');
INSERT INTO elem_voc VALUES ('475', 'question', '問題', '名詞');
INSERT INTO elem_voc VALUES ('476', 'quiet', '安靜的', '形容詞');
INSERT INTO elem_voc VALUES ('477', 'rabbit', '兔子', '名詞');
INSERT INTO elem_voc VALUES ('478', 'rain', '雨水', '名詞');
INSERT INTO elem_voc VALUES ('479', 'rain', '下雨', '動詞');
INSERT INTO elem_voc VALUES ('480', 'rainbow', '彩虹', '名詞');
INSERT INTO elem_voc VALUES ('481', 'rainy', '下雨的/多雨的', '形容詞');
INSERT INTO elem_voc VALUES ('482', 'read', '閱讀', '動詞');
INSERT INTO elem_voc VALUES ('483', 'ready', '準備好的', '形容詞');
INSERT INTO elem_voc VALUES ('484', 'really', '真正地', '副詞');
INSERT INTO elem_voc VALUES ('485', 'red', '紅色的', '形容詞');
INSERT INTO elem_voc VALUES ('486', 'refrigerator', '電冰箱 (= fridge)', '名詞');
INSERT INTO elem_voc VALUES ('487', 'restaurant', '餐廳', '名詞');
INSERT INTO elem_voc VALUES ('488', 'restroom', '洗手間、廁所', '名詞');
INSERT INTO elem_voc VALUES ('489', 'rice', '米飯', '名詞');
INSERT INTO elem_voc VALUES ('490', 'ride', '騎（機車、腳踏車等）', '動詞');
INSERT INTO elem_voc VALUES ('491', 'right', '對的', '形容詞');
INSERT INTO elem_voc VALUES ('492', 'right', '右邊', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('493', 'river', '河流', '名詞');
INSERT INTO elem_voc VALUES ('494', 'robot', '機器人', '名詞');
INSERT INTO elem_voc VALUES ('495', 'ruler', '尺', '名詞');
INSERT INTO elem_voc VALUES ('496', 'run', '跑、跑步', '動詞');
INSERT INTO elem_voc VALUES ('497', 'table', '桌子', '名詞');
INSERT INTO elem_voc VALUES ('498', 'take', '攜帶、拿取', '動詞');
INSERT INTO elem_voc VALUES ('499', 'talk', '說話、談話', '動詞');
INSERT INTO elem_voc VALUES ('500', 'tall', '高的', '形容詞');
INSERT INTO elem_voc VALUES ('501', 'taste', '嚐起來', '動詞');
INSERT INTO elem_voc VALUES ('502', 'taxi', '計程車', '名詞');
INSERT INTO elem_voc VALUES ('503', 'tea', '茶', '名詞');
INSERT INTO elem_voc VALUES ('504', 'teacher', '老師', '名詞');
INSERT INTO elem_voc VALUES ('505', 'teeth', '牙齒 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('506', 'telephone', '電話', '名詞');
INSERT INTO elem_voc VALUES ('507', 'television', '電視 (= TV)', '名詞');
INSERT INTO elem_voc VALUES ('508', 'tell', '告訴、告知', '動詞');
INSERT INTO elem_voc VALUES ('509', 'ten', '十', '數字');
INSERT INTO elem_voc VALUES ('510', 'test', '考試', '名詞');
INSERT INTO elem_voc VALUES ('511', 'than', '比', '介系詞');
INSERT INTO elem_voc VALUES ('512', 'thank', '感謝（某人）', '動詞');
INSERT INTO elem_voc VALUES ('513', 'that', '那個', '限定詞');
INSERT INTO elem_voc VALUES ('514', 'the', '這', '冠詞');
INSERT INTO elem_voc VALUES ('515', 'their', '他們的', '限定詞');
INSERT INTO elem_voc VALUES ('516', 'them', '他們(受詞)', '代名詞');
INSERT INTO elem_voc VALUES ('517', 'then', '然後、接著', '副詞');
INSERT INTO elem_voc VALUES ('518', 'there', '那裡', '副詞');
INSERT INTO elem_voc VALUES ('519', 'these', '這些', '限定詞');
INSERT INTO elem_voc VALUES ('520', 'they', '他們', '代名詞');
INSERT INTO elem_voc VALUES ('521', 'thin', '瘦的', '形容詞');
INSERT INTO elem_voc VALUES ('522', 'thing', '東西、物', '名詞');
INSERT INTO elem_voc VALUES ('523', 'third', '第三', '數字');
INSERT INTO elem_voc VALUES ('524', 'thirsty', '口渴的', '形容詞');
INSERT INTO elem_voc VALUES ('525', 'thirteen', '十三', '數字');
INSERT INTO elem_voc VALUES ('526', 'thirty', '三十', '數字');
INSERT INTO elem_voc VALUES ('527', 'this', '這個', '限定詞');
INSERT INTO elem_voc VALUES ('528', 'those', '那些', '限定詞');
INSERT INTO elem_voc VALUES ('529', 'three', '三', '數字');
INSERT INTO elem_voc VALUES ('530', 'Thursday', '星期四', '名詞');
INSERT INTO elem_voc VALUES ('531', 'ticket', '票', '名詞');
INSERT INTO elem_voc VALUES ('532', 'tiger', '老虎', '名詞');
INSERT INTO elem_voc VALUES ('533', 'time', '時間', '名詞');
INSERT INTO elem_voc VALUES ('534', 'tired', '疲累的', '形容詞');
INSERT INTO elem_voc VALUES ('535', 'to', '向、朝、對著', '介系詞');
INSERT INTO elem_voc VALUES ('536', 'today', '今天', '名詞');
INSERT INTO elem_voc VALUES ('537', 'together', '一起', '副詞');
INSERT INTO elem_voc VALUES ('538', 'tomorrow', '明天', '名詞');
INSERT INTO elem_voc VALUES ('539', 'too', '1. 也；2. 太...', '副詞');
INSERT INTO elem_voc VALUES ('540', 'tooth', '牙齒', '名詞');
INSERT INTO elem_voc VALUES ('541', 'toothache', '牙痛', '名詞');
INSERT INTO elem_voc VALUES ('542', 'touch', '觸碰', '動詞');
INSERT INTO elem_voc VALUES ('543', 'towel', '毛巾', '名詞');
INSERT INTO elem_voc VALUES ('544', 'toy', '玩具', '名詞');
INSERT INTO elem_voc VALUES ('545', 'train', '火車', '名詞');
INSERT INTO elem_voc VALUES ('546', 'trash', '垃圾', '名詞');
INSERT INTO elem_voc VALUES ('547', 'tree', '樹', '名詞');
INSERT INTO elem_voc VALUES ('548', 'trip', '（短程的）旅行', '名詞');
INSERT INTO elem_voc VALUES ('549', 'truck', '卡車', '名詞');
INSERT INTO elem_voc VALUES ('550', 'try', '嘗試', '動詞');
INSERT INTO elem_voc VALUES ('551', 'T-shirt', 'T 恤', '名詞');
INSERT INTO elem_voc VALUES ('552', 'Tuesday', '星期二', '名詞');
INSERT INTO elem_voc VALUES ('553', 'turn', '轉彎', '動詞');
INSERT INTO elem_voc VALUES ('554', 'turtle', '烏龜', '名詞');
INSERT INTO elem_voc VALUES ('555', 'TV', '電視 (= television)', '名詞');
INSERT INTO elem_voc VALUES ('556', 'twelve', '十二', '數字');
INSERT INTO elem_voc VALUES ('557', 'twenty', '二十', '數字');
INSERT INTO elem_voc VALUES ('558', 'two', '二', '數字');
INSERT INTO elem_voc VALUES ('559', 'typhoon', '颱風', '名詞');
INSERT INTO elem_voc VALUES ('560', 'table', '桌子', '名詞');
INSERT INTO elem_voc VALUES ('561', 'take', '攜帶、拿取', '動詞');
INSERT INTO elem_voc VALUES ('562', 'talk', '說話、談話', '動詞');
INSERT INTO elem_voc VALUES ('563', 'tall', '高的', '形容詞');
INSERT INTO elem_voc VALUES ('564', 'taste', '嚐起來', '動詞');
INSERT INTO elem_voc VALUES ('565', 'taxi', '計程車', '名詞');
INSERT INTO elem_voc VALUES ('566', 'tea', '茶', '名詞');
INSERT INTO elem_voc VALUES ('567', 'teacher', '老師', '名詞');
INSERT INTO elem_voc VALUES ('568', 'teeth', '牙齒 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('569', 'telephone', '電話', '名詞');
INSERT INTO elem_voc VALUES ('570', 'television', '電視 (= TV)', '名詞');
INSERT INTO elem_voc VALUES ('571', 'tell', '告訴、告知', '動詞');
INSERT INTO elem_voc VALUES ('572', 'ten', '十', '數字');
INSERT INTO elem_voc VALUES ('573', 'test', '考試', '名詞');
INSERT INTO elem_voc VALUES ('574', 'than', '比', '介系詞');
INSERT INTO elem_voc VALUES ('575', 'thank', '感謝（某人）', '動詞');
INSERT INTO elem_voc VALUES ('576', 'that', '那個', '限定詞');
INSERT INTO elem_voc VALUES ('577', 'the', '這', '冠詞');
INSERT INTO elem_voc VALUES ('578', 'their', '他們的', '限定詞');
INSERT INTO elem_voc VALUES ('579', 'them', '他們(受詞)', '代名詞');
INSERT INTO elem_voc VALUES ('580', 'then', '然後、接著', '副詞');
INSERT INTO elem_voc VALUES ('581', 'there', '那裡', '副詞');
INSERT INTO elem_voc VALUES ('582', 'these', '這些', '限定詞');
INSERT INTO elem_voc VALUES ('583', 'they', '他們', '代名詞');
INSERT INTO elem_voc VALUES ('584', 'thin', '瘦的', '形容詞');
INSERT INTO elem_voc VALUES ('585', 'thing', '東西、物', '名詞');
INSERT INTO elem_voc VALUES ('586', 'third', '第三', '數字');
INSERT INTO elem_voc VALUES ('587', 'thirsty', '口渴的', '形容詞');
INSERT INTO elem_voc VALUES ('588', 'thirteen', '十三', '數字');
INSERT INTO elem_voc VALUES ('589', 'thirty', '三十', '數字');
INSERT INTO elem_voc VALUES ('590', 'this', '這個', '限定詞');
INSERT INTO elem_voc VALUES ('591', 'those', '那些', '限定詞');
INSERT INTO elem_voc VALUES ('592', 'three', '三', '數字');
INSERT INTO elem_voc VALUES ('593', 'Thursday', '星期四', '名詞');
INSERT INTO elem_voc VALUES ('594', 'ticket', '票', '名詞');
INSERT INTO elem_voc VALUES ('595', 'tiger', '老虎', '名詞');
INSERT INTO elem_voc VALUES ('596', 'time', '時間', '名詞');
INSERT INTO elem_voc VALUES ('597', 'tired', '疲累的', '形容詞');
INSERT INTO elem_voc VALUES ('598', 'to', '向、朝、對著', '介系詞');
INSERT INTO elem_voc VALUES ('599', 'today', '今天', '名詞');
INSERT INTO elem_voc VALUES ('600', 'together', '一起', '副詞');
INSERT INTO elem_voc VALUES ('601', 'tomorrow', '明天', '名詞');
INSERT INTO elem_voc VALUES ('602', 'too', '1. 也；2. 太...', '副詞');
INSERT INTO elem_voc VALUES ('603', 'tooth', '牙齒', '名詞');
INSERT INTO elem_voc VALUES ('604', 'toothache', '牙痛', '名詞');
INSERT INTO elem_voc VALUES ('605', 'touch', '觸碰', '動詞');
INSERT INTO elem_voc VALUES ('606', 'towel', '毛巾', '名詞');
INSERT INTO elem_voc VALUES ('607', 'toy', '玩具', '名詞');
INSERT INTO elem_voc VALUES ('608', 'train', '火車', '名詞');
INSERT INTO elem_voc VALUES ('609', 'trash', '垃圾', '名詞');
INSERT INTO elem_voc VALUES ('610', 'tree', '樹', '名詞');
INSERT INTO elem_voc VALUES ('611', 'trip', '（短程的）旅行', '名詞');
INSERT INTO elem_voc VALUES ('612', 'truck', '卡車', '名詞');
INSERT INTO elem_voc VALUES ('613', 'try', '嘗試', '動詞');
INSERT INTO elem_voc VALUES ('614', 'T-shirt', 'T 恤', '名詞');
INSERT INTO elem_voc VALUES ('615', 'Tuesday', '星期二', '名詞');
INSERT INTO elem_voc VALUES ('616', 'turn', '轉彎', '動詞');
INSERT INTO elem_voc VALUES ('617', 'turtle', '烏龜', '名詞');
INSERT INTO elem_voc VALUES ('618', 'TV', '電視 (= television)', '名詞');
INSERT INTO elem_voc VALUES ('619', 'twelve', '十二', '數字');
INSERT INTO elem_voc VALUES ('620', 'twenty', '二十', '數字');
INSERT INTO elem_voc VALUES ('621', 'two', '二', '數字');
INSERT INTO elem_voc VALUES ('622', 'typhoon', '颱風', '名詞');
INSERT INTO elem_voc VALUES ('623', 'umbrella', '傘', '名詞');
INSERT INTO elem_voc VALUES ('624', 'uncle', '叔叔、舅舅、姑丈、姨丈', '名詞');
INSERT INTO elem_voc VALUES ('625', 'under', '在...下方', '介系詞');
INSERT INTO elem_voc VALUES ('626', 'up', '向上', '介系詞');
INSERT INTO elem_voc VALUES ('627', 'us', '我們(受詞)', '代名詞');
INSERT INTO elem_voc VALUES ('628', 'usually', '通常', '副詞');
INSERT INTO elem_voc VALUES ('629', 'vacation', '假期', '名詞');
INSERT INTO elem_voc VALUES ('630', 'very', '非常', '副詞');
INSERT INTO elem_voc VALUES ('631', 'wait', '等、等待', '動詞');
INSERT INTO elem_voc VALUES ('632', 'waiter', '男服務生', '名詞');
INSERT INTO elem_voc VALUES ('633', 'waitress', '女服務生', '名詞');
INSERT INTO elem_voc VALUES ('634', 'wake', '醒來、喚醒', '動詞');
INSERT INTO elem_voc VALUES ('635', 'walk', '走路', '動詞');
INSERT INTO elem_voc VALUES ('636', 'wall', '牆壁', '名詞');
INSERT INTO elem_voc VALUES ('637', 'want', '想要', '動詞');
INSERT INTO elem_voc VALUES ('638', 'warm', '溫暖的', '形容詞');
INSERT INTO elem_voc VALUES ('639', 'wash', '洗', '動詞');
INSERT INTO elem_voc VALUES ('640', 'watch', '手錶', '名詞');
INSERT INTO elem_voc VALUES ('641', 'watch', '看', '動詞');
INSERT INTO elem_voc VALUES ('642', 'water', '水', '名詞');
INSERT INTO elem_voc VALUES ('643', 'watermelon', '西瓜', '名詞');
INSERT INTO elem_voc VALUES ('644', 'way', '路、方向', '名詞');
INSERT INTO elem_voc VALUES ('645', 'we', '我們', '代名詞');
INSERT INTO elem_voc VALUES ('646', 'wear', '穿、戴', '動詞');
INSERT INTO elem_voc VALUES ('647', 'weather', '天氣', '名詞');
INSERT INTO elem_voc VALUES ('648', 'Wednesday', '星期三', '名詞');
INSERT INTO elem_voc VALUES ('649', 'week', '星期', '名詞');
INSERT INTO elem_voc VALUES ('650', 'welcome', '歡迎', '動詞');
INSERT INTO elem_voc VALUES ('651', 'well', '好的, 健康地', '形容詞, 副詞');
INSERT INTO elem_voc VALUES ('652', 'wet', '潮濕的', '形容詞');
INSERT INTO elem_voc VALUES ('653', 'wet', '濕的', '形容詞');
INSERT INTO elem_voc VALUES ('654', 'whale', '鯨魚', '名詞');
INSERT INTO elem_voc VALUES ('655', 'what', '什麼...', '代名詞');
INSERT INTO elem_voc VALUES ('656', 'when', '何時...', '副詞');
INSERT INTO elem_voc VALUES ('657', 'where', '在哪裡...', '副詞');
INSERT INTO elem_voc VALUES ('658', 'which', '哪一個...', '限定詞');
INSERT INTO elem_voc VALUES ('659', 'white', '白色的', '形容詞');
INSERT INTO elem_voc VALUES ('660', 'who', '誰...', '代名詞');
INSERT INTO elem_voc VALUES ('661', 'whose', '誰的...', '限定詞');
INSERT INTO elem_voc VALUES ('662', 'why', '為什麼...', '副詞');
INSERT INTO elem_voc VALUES ('663', 'will', '將會', '助動詞');
INSERT INTO elem_voc VALUES ('664', 'win', '贏', '動詞');
INSERT INTO elem_voc VALUES ('665', 'wind', '風', '名詞');
INSERT INTO elem_voc VALUES ('666', 'window', '窗戶', '名詞');
INSERT INTO elem_voc VALUES ('667', 'windy', '風大的', '形容詞');
INSERT INTO elem_voc VALUES ('668', 'winter', '冬天', '名詞');
INSERT INTO elem_voc VALUES ('669', 'with', '和...一起', '介系詞');
INSERT INTO elem_voc VALUES ('670', 'woman', '女人', '名詞');
INSERT INTO elem_voc VALUES ('671', 'women', '女人 (複數)', '名詞');
INSERT INTO elem_voc VALUES ('672', 'wonderful', '很棒的、精彩的', '形容詞');
INSERT INTO elem_voc VALUES ('673', 'word', '字', '名詞');
INSERT INTO elem_voc VALUES ('674', 'work', '工作', '名詞');
INSERT INTO elem_voc VALUES ('675', 'worker', '工作者', '名詞');
INSERT INTO elem_voc VALUES ('676', 'worry', '擔心', '動詞');
INSERT INTO elem_voc VALUES ('677', 'write', '寫', '動詞');
INSERT INTO elem_voc VALUES ('679', 'year', '年', '名詞');
INSERT INTO elem_voc VALUES ('680', 'yellow', '黃色的', '形容詞');
INSERT INTO elem_voc VALUES ('681', 'yes', '是', '副詞');
INSERT INTO elem_voc VALUES ('682', 'yesterday', '昨天', '名詞');
INSERT INTO elem_voc VALUES ('683', 'you', '你；你們', '代名詞');
INSERT INTO elem_voc VALUES ('684', 'young', '年輕的', '形容詞');
INSERT INTO elem_voc VALUES ('685', 'your', '你的、你們的', '限定詞');
INSERT INTO elem_voc VALUES ('686', 'yummy', '好吃的、美味的', '形容詞');
