CREATE TABLE elem_voc (
    orders int,
    vocabulay varchar(300),
    definition	nvarchar(300),
    part_of_speech nvarchar(300)
);

INSERT INTO elem_voc VALUES ('0', 'a', N'一個', N'冠詞');
INSERT INTO elem_voc VALUES ('1', 'about', N'1. 大約；2. 關於...', N'介系詞');
INSERT INTO elem_voc VALUES ('2', 'actor', N'男演員', N'名詞');
INSERT INTO elem_voc VALUES ('3', 'actress', N'女演員', N'名詞');
INSERT INTO elem_voc VALUES ('4', 'after', N'在...之後', N'介系詞');
INSERT INTO elem_voc VALUES ('5', 'afternoon', N'下午', N'名詞');
INSERT INTO elem_voc VALUES ('6', 'again', N'再一次、又一次', N'副詞');
INSERT INTO elem_voc VALUES ('7', 'airplane', N'飛機 (= plane)', N'名詞');
INSERT INTO elem_voc VALUES ('8', 'airport', N'機場', N'名詞');
INSERT INTO elem_voc VALUES ('9', 'all', N'全部的', N'限定詞');
INSERT INTO elem_voc VALUES ('10', 'always', N'總是、永遠', N'副詞');
INSERT INTO elem_voc VALUES ('11', 'an', N'一個', N'冠詞');
INSERT INTO elem_voc VALUES ('12', 'and', N'和', N'連接詞');
INSERT INTO elem_voc VALUES ('13', 'angry', N'生氣的', N'形容詞');
INSERT INTO elem_voc VALUES ('14', 'animal', N'動物', N'名詞');
INSERT INTO elem_voc VALUES ('15', 'answer', N'回答', N'動詞');
INSERT INTO elem_voc VALUES ('16', 'apple', N'蘋果', N'名詞');
INSERT INTO elem_voc VALUES ('17', 'April', N'四月', N'名詞');
INSERT INTO elem_voc VALUES ('18', 'arm', N'手臂', N'名詞');
INSERT INTO elem_voc VALUES ('19', 'art', N'美術、藝術', N'名詞');
INSERT INTO elem_voc VALUES ('20', 'ask', N'問', N'動詞');
INSERT INTO elem_voc VALUES ('21', 'at', N'在(某處)、在(時刻)', N'介系詞');
INSERT INTO elem_voc VALUES ('22', 'August', N'八月', N'名詞');
INSERT INTO elem_voc VALUES ('23', 'aunt', N'阿姨、姑姑、伯母、舅媽', N'名詞');
INSERT INTO elem_voc VALUES ('24', 'away', N'離開', N'副詞');
INSERT INTO elem_voc VALUES ('25', 'a', N'一個', N'冠詞');
INSERT INTO elem_voc VALUES ('26', 'about', N'1. 大約；2. 關於...', N'介系詞');
INSERT INTO elem_voc VALUES ('27', 'actor', N'男演員', N'名詞');
INSERT INTO elem_voc VALUES ('28', 'actress', N'女演員', N'名詞');
INSERT INTO elem_voc VALUES ('29', 'after', N'在...之後', N'介系詞');
INSERT INTO elem_voc VALUES ('30', 'afternoon', N'下午', N'名詞');
INSERT INTO elem_voc VALUES ('31', 'again', N'再一次、又一次', N'副詞');
INSERT INTO elem_voc VALUES ('32', 'airplane', N'飛機 (= plane)', N'名詞');
INSERT INTO elem_voc VALUES ('33', 'airport', N'機場', N'名詞');
INSERT INTO elem_voc VALUES ('34', 'all', N'全部的', N'限定詞');
INSERT INTO elem_voc VALUES ('35', 'always', N'總是、永遠', N'副詞');
INSERT INTO elem_voc VALUES ('36', 'an', N'一個', N'冠詞');
INSERT INTO elem_voc VALUES ('37', 'and', N'和', N'連接詞');
INSERT INTO elem_voc VALUES ('38', 'angry', N'生氣的', N'形容詞');
INSERT INTO elem_voc VALUES ('39', 'animal', N'動物', N'名詞');
INSERT INTO elem_voc VALUES ('40', 'answer', N'回答', N'動詞');
INSERT INTO elem_voc VALUES ('41', 'apple', N'蘋果', N'名詞');
INSERT INTO elem_voc VALUES ('42', 'April', N'四月', N'名詞');
INSERT INTO elem_voc VALUES ('43', 'arm', N'手臂', N'名詞');
INSERT INTO elem_voc VALUES ('44', 'art', N'美術、藝術', N'名詞');
INSERT INTO elem_voc VALUES ('45', 'ask', N'問', N'動詞');
INSERT INTO elem_voc VALUES ('46', 'at', N'在(某處)、在(時刻)', N'介系詞');
INSERT INTO elem_voc VALUES ('47', 'August', N'八月', N'名詞');
INSERT INTO elem_voc VALUES ('48', 'aunt', N'阿姨、姑姑、伯母、舅媽', N'名詞');
INSERT INTO elem_voc VALUES ('49', 'away', N'離開', N'副詞');
INSERT INTO elem_voc VALUES ('50', 'baby', N'嬰兒', N'名詞');
INSERT INTO elem_voc VALUES ('51', 'back', N'背', N'名詞');
INSERT INTO elem_voc VALUES ('52', 'back', N'向後、回原處', N'副詞');
INSERT INTO elem_voc VALUES ('53', 'bad', N'不好的、壞的', N'形容詞');
INSERT INTO elem_voc VALUES ('54', 'bag', N'袋子', N'名詞');
INSERT INTO elem_voc VALUES ('55', 'ball', N'球', N'名詞');
INSERT INTO elem_voc VALUES ('56', 'banana', N'香蕉', N'名詞');
INSERT INTO elem_voc VALUES ('57', 'bank', N'銀行', N'名詞');
INSERT INTO elem_voc VALUES ('58', 'baseball', N'棒球', N'名詞');
INSERT INTO elem_voc VALUES ('59', 'basketball', N'籃球', N'名詞');
INSERT INTO elem_voc VALUES ('60', 'bathroom', N'浴室', N'名詞');
INSERT INTO elem_voc VALUES ('61', 'be', N'是 (is, am, are)', N'助動詞');
INSERT INTO elem_voc VALUES ('62', 'beach', N'海灘', N'名詞');
INSERT INTO elem_voc VALUES ('63', 'bear', N'熊', N'名詞');
INSERT INTO elem_voc VALUES ('64', 'beautiful', N'美麗的、漂亮的', N'形容詞');
INSERT INTO elem_voc VALUES ('65', 'because', N'因為', N'連接詞');
INSERT INTO elem_voc VALUES ('66', 'bed', N'床', N'名詞');
INSERT INTO elem_voc VALUES ('67', 'bedroom', N'臥房', N'名詞');
INSERT INTO elem_voc VALUES ('68', 'bee', N'蜜蜂', N'名詞');
INSERT INTO elem_voc VALUES ('69', 'beef', N'牛肉', N'名詞');
INSERT INTO elem_voc VALUES ('70', 'before', N'在...之前', N'介系詞, 連接詞');
INSERT INTO elem_voc VALUES ('71', 'behind', N'在...後面', N'介系詞');
INSERT INTO elem_voc VALUES ('72', 'bicycle', N'腳踏車 (= bike)', N'名詞');
INSERT INTO elem_voc VALUES ('73', 'big', N'大的', N'形容詞');
INSERT INTO elem_voc VALUES ('74', 'bike', N'腳踏車 (= bicycle)', N'名詞');
INSERT INTO elem_voc VALUES ('75', 'bird', N'鳥', N'名詞');
INSERT INTO elem_voc VALUES ('76', 'birthday', N'生日', N'名詞');
INSERT INTO elem_voc VALUES ('77', 'bite', N'咬', N'動詞');
INSERT INTO elem_voc VALUES ('78', 'black', N'黑色的', N'形容詞');
INSERT INTO elem_voc VALUES ('79', 'blackboard', N'黑板', N'名詞');
INSERT INTO elem_voc VALUES ('80', 'blue', N'藍色的', N'形容詞');
INSERT INTO elem_voc VALUES ('81', 'boat', N'船', N'名詞');
INSERT INTO elem_voc VALUES ('82', 'book', N'書、書本', N'名詞');
INSERT INTO elem_voc VALUES ('83', 'bookstore', N'書店', N'名詞');
INSERT INTO elem_voc VALUES ('84', 'bored', N'覺得無聊的', N'形容詞');
INSERT INTO elem_voc VALUES ('85', 'boring', N'令人無聊的', N'形容詞');
INSERT INTO elem_voc VALUES ('86', 'both', N'兩個都', N'限定詞');
INSERT INTO elem_voc VALUES ('87', 'bottle', N'瓶子', N'名詞');
INSERT INTO elem_voc VALUES ('88', 'box', N'箱子', N'名詞');
INSERT INTO elem_voc VALUES ('89', 'boy', N'男孩', N'名詞');
INSERT INTO elem_voc VALUES ('90', 'bread', N'麵包', N'名詞');
INSERT INTO elem_voc VALUES ('91', 'breakfast', N'早餐', N'名詞');
INSERT INTO elem_voc VALUES ('92', 'brother', N'哥哥、弟弟', N'名詞');
INSERT INTO elem_voc VALUES ('93', 'brown', N'咖啡色的', N'形容詞');
INSERT INTO elem_voc VALUES ('94', 'brush', N'用刷子刷', N'動詞');
INSERT INTO elem_voc VALUES ('95', 'bus', N'公車', N'名詞');
INSERT INTO elem_voc VALUES ('96', 'bus stop', N'公車站', N'名詞');
INSERT INTO elem_voc VALUES ('97', 'busy', N'忙碌的', N'形容詞');
INSERT INTO elem_voc VALUES ('98', 'but', N'但是', N'連接詞');
INSERT INTO elem_voc VALUES ('99', 'butterfly', N'蝴蝶', N'名詞');
INSERT INTO elem_voc VALUES ('100', 'buy', N'買', N'動詞');
INSERT INTO elem_voc VALUES ('101', 'by', N'在...旁邊', N'介系詞');
INSERT INTO elem_voc VALUES ('102', 'bye', N'再見 (= goodbye)', N'感嘆詞');
INSERT INTO elem_voc VALUES ('103', 'cake', N'蛋糕', N'名詞');
INSERT INTO elem_voc VALUES ('104', 'call', N'打電話給...', N'動詞');
INSERT INTO elem_voc VALUES ('105', 'can', N'可以', N'助動詞');
INSERT INTO elem_voc VALUES ('106', 'can', N'罐子', N'名詞');
INSERT INTO elem_voc VALUES ('107', 'candy', N'糖果', N'名詞');
INSERT INTO elem_voc VALUES ('108', 'cap', N'棒球帽', N'名詞');
INSERT INTO elem_voc VALUES ('109', 'car', N'車子', N'名詞');
INSERT INTO elem_voc VALUES ('110', 'card', N'卡片', N'名詞');
INSERT INTO elem_voc VALUES ('111', 'cat', N'貓', N'名詞');
INSERT INTO elem_voc VALUES ('112', 'cellphone', N'手機', N'名詞');
INSERT INTO elem_voc VALUES ('113', 'chair', N'椅子', N'名詞');
INSERT INTO elem_voc VALUES ('114', 'chicken', N'雞', N'名詞');
INSERT INTO elem_voc VALUES ('115', 'chicken', N'雞肉', N'名詞');
INSERT INTO elem_voc VALUES ('116', 'Chinese', N'中文', N'名詞');
INSERT INTO elem_voc VALUES ('117', 'chocolate', N'巧克力', N'名詞');
INSERT INTO elem_voc VALUES ('118', 'chopsticks', N'筷子', N'名詞');
INSERT INTO elem_voc VALUES ('119', 'class', N'課；班級', N'名詞');
INSERT INTO elem_voc VALUES ('120', 'classroom', N'教室', N'名詞');
INSERT INTO elem_voc VALUES ('121', 'clean', N'乾淨的', N'形容詞');
INSERT INTO elem_voc VALUES ('122', 'clean', N'清理', N'動詞');
INSERT INTO elem_voc VALUES ('123', 'climb', N'爬、攀爬', N'動詞');
INSERT INTO elem_voc VALUES ('124', 'clock', N'時鐘', N'名詞');
INSERT INTO elem_voc VALUES ('125', 'close', N'關', N'動詞');
INSERT INTO elem_voc VALUES ('126', 'clothes', N'衣服', N'名詞');
INSERT INTO elem_voc VALUES ('127', 'cloudy', N'多雲的', N'形容詞');
INSERT INTO elem_voc VALUES ('128', 'coat', N'外套', N'名詞');
INSERT INTO elem_voc VALUES ('129', 'coffee', N'咖啡', N'名詞');
INSERT INTO elem_voc VALUES ('130', 'coke', N'可樂', N'名詞');
INSERT INTO elem_voc VALUES ('131', 'cold', N'寒冷的', N'形容詞');
INSERT INTO elem_voc VALUES ('132', 'cold', N'感冒', N'名詞');
INSERT INTO elem_voc VALUES ('133', 'color', N'顏色', N'名詞');
INSERT INTO elem_voc VALUES ('134', 'come', N'來', N'動詞');
INSERT INTO elem_voc VALUES ('135', 'computer', N'電腦', N'名詞');
INSERT INTO elem_voc VALUES ('136', 'cook', N'廚師', N'名詞');
INSERT INTO elem_voc VALUES ('137', 'cook', N'做飯', N'動詞');
INSERT INTO elem_voc VALUES ('138', 'cookies', N'餅乾', N'名詞');
INSERT INTO elem_voc VALUES ('139', 'cool', N'涼爽的', N'形容詞');
INSERT INTO elem_voc VALUES ('140', 'cool', N'清涼的', N'形容詞');
INSERT INTO elem_voc VALUES ('141', 'cousin', N'堂兄（弟、姊、妹）', N'名詞');
INSERT INTO elem_voc VALUES ('142', 'cow', N'乳牛', N'名詞');
INSERT INTO elem_voc VALUES ('143', 'cry', N'哭、哭泣', N'動詞');
INSERT INTO elem_voc VALUES ('144', 'cup', N'杯子', N'名詞');
INSERT INTO elem_voc VALUES ('145', 'cute', N'可愛的', N'形容詞');
INSERT INTO elem_voc VALUES ('146', 'dad', N'爸爸 (= father; daddy)', N'名詞');
INSERT INTO elem_voc VALUES ('147', 'daddy', N'爸爸 (= father; dad)', N'名詞');
INSERT INTO elem_voc VALUES ('148', 'dance', N'跳舞', N'動詞');
INSERT INTO elem_voc VALUES ('149', 'daughter', N'女兒', N'名詞');
INSERT INTO elem_voc VALUES ('150', 'day', N'天', N'名詞');
INSERT INTO elem_voc VALUES ('151', 'December', N'十二月', N'名詞');
INSERT INTO elem_voc VALUES ('152', 'department store', N'百貨公司', N'名詞');
INSERT INTO elem_voc VALUES ('153', 'desk', N'桌子', N'名詞');
INSERT INTO elem_voc VALUES ('154', 'different', N'不一樣的', N'形容詞');
INSERT INTO elem_voc VALUES ('155', 'dining room', N'(家裡的)餐廳', N'名詞');
INSERT INTO elem_voc VALUES ('156', 'dinner', N'晚餐', N'名詞');
INSERT INTO elem_voc VALUES ('157', 'dirty', N'髒的', N'形容詞');
INSERT INTO elem_voc VALUES ('158', 'dish', N'碟子、盤子', N'名詞');
INSERT INTO elem_voc VALUES ('159', 'do', N'助動詞', N'助動詞');
INSERT INTO elem_voc VALUES ('160', 'do', N'做', N'動詞');
INSERT INTO elem_voc VALUES ('161', 'doctor', N'醫生', N'名詞');
INSERT INTO elem_voc VALUES ('162', 'dog', N'狗', N'名詞');
INSERT INTO elem_voc VALUES ('163', 'doll', N'玩偶', N'名詞');
INSERT INTO elem_voc VALUES ('164', 'dollar', N'元', N'名詞');
INSERT INTO elem_voc VALUES ('165', 'door', N'門', N'名詞');
INSERT INTO elem_voc VALUES ('166', 'draw', N'畫、描畫', N'動詞');
INSERT INTO elem_voc VALUES ('167', 'dream', N'夢', N'名詞');
INSERT INTO elem_voc VALUES ('168', 'dress', N'洋裝', N'名詞');
INSERT INTO elem_voc VALUES ('169', 'drink', N'喝', N'動詞');
INSERT INTO elem_voc VALUES ('170', 'drive', N'開車', N'動詞');
INSERT INTO elem_voc VALUES ('171', 'driver', N'司機、駕駛員', N'名詞');
INSERT INTO elem_voc VALUES ('172', 'drum', N'鼓', N'名詞');
INSERT INTO elem_voc VALUES ('173', 'duck', N'鴨子', N'名詞');
INSERT INTO elem_voc VALUES ('174', 'duck', N'鴨肉', N'名詞');
INSERT INTO elem_voc VALUES ('175', 'dumpling', N'水餃', N'名詞');
INSERT INTO elem_voc VALUES ('176', 'ear', N'耳朵', N'名詞');
INSERT INTO elem_voc VALUES ('177', 'early', N'早到（的）', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('178', 'easy', N'簡單的', N'形容詞');
INSERT INTO elem_voc VALUES ('179', 'eat', N'吃', N'動詞');
INSERT INTO elem_voc VALUES ('180', 'egg', N'蛋', N'名詞');
INSERT INTO elem_voc VALUES ('181', 'eight', N'八', N'數字');
INSERT INTO elem_voc VALUES ('182', 'eighteen', N'十八', N'數字');
INSERT INTO elem_voc VALUES ('183', 'eighty', N'八十', N'數字');
INSERT INTO elem_voc VALUES ('184', 'elephant', N'大象', N'名詞');
INSERT INTO elem_voc VALUES ('185', 'eleven', N'十一', N'數字');
INSERT INTO elem_voc VALUES ('186', 'email', N'電子郵件', N'名詞');
INSERT INTO elem_voc VALUES ('187', 'English', N'英文', N'名詞');
INSERT INTO elem_voc VALUES ('188', 'enjoy', N'享受、喜歡', N'動詞');
INSERT INTO elem_voc VALUES ('189', 'eraser', N'橡皮擦', N'名詞');
INSERT INTO elem_voc VALUES ('190', 'evening', N'傍晚', N'名詞');
INSERT INTO elem_voc VALUES ('191', 'every', N'每一個', N'限定詞');
INSERT INTO elem_voc VALUES ('192', 'excited', N'覺得興奮的', N'形容詞');
INSERT INTO elem_voc VALUES ('193', 'exciting', N'令人興奮的', N'形容詞');
INSERT INTO elem_voc VALUES ('194', 'excuse me', N'不好意思、對不起', N'感嘆詞');
INSERT INTO elem_voc VALUES ('195', 'eye', N'眼睛', N'名詞');
INSERT INTO elem_voc VALUES ('196', 'face', N'臉', N'名詞');
INSERT INTO elem_voc VALUES ('197', 'fall', N'秋天', N'名詞');
INSERT INTO elem_voc VALUES ('198', 'fall', N'掉落', N'動詞');
INSERT INTO elem_voc VALUES ('199', 'family', N'家庭、家人', N'名詞');
INSERT INTO elem_voc VALUES ('200', 'fan', N'電扇', N'名詞');
INSERT INTO elem_voc VALUES ('201', 'farmer', N'農夫', N'名詞');
INSERT INTO elem_voc VALUES ('202', 'fast', N'快速的（地）', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('203', 'father', N'爸爸 (= dad; daddy)', N'名詞');
INSERT INTO elem_voc VALUES ('204', 'favorite', N'最喜歡的', N'形容詞');
INSERT INTO elem_voc VALUES ('205', 'February', N'二月', N'名詞');
INSERT INTO elem_voc VALUES ('206', 'feel', N'感受、感覺', N'動詞');
INSERT INTO elem_voc VALUES ('207', 'feet', N'腳 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('208', 'fifteen', N'十五', N'數字');
INSERT INTO elem_voc VALUES ('209', 'fifty', N'五十', N'數字');
INSERT INTO elem_voc VALUES ('210', 'find', N'找', N'動詞');
INSERT INTO elem_voc VALUES ('211', 'fine', N'很好的、很不錯的', N'形容詞');
INSERT INTO elem_voc VALUES ('212', 'fire station', N'消防站', N'名詞');
INSERT INTO elem_voc VALUES ('213', 'first', N'第一', N'數字');
INSERT INTO elem_voc VALUES ('214', 'fish', N'魚', N'名詞');
INSERT INTO elem_voc VALUES ('215', 'fish', N'魚肉', N'名詞');
INSERT INTO elem_voc VALUES ('216', 'fish', N'釣魚', N'動詞');
INSERT INTO elem_voc VALUES ('217', 'five', N'五', N'數字');
INSERT INTO elem_voc VALUES ('218', 'floor', N'地板', N'名詞');
INSERT INTO elem_voc VALUES ('219', 'flower', N'花', N'名詞');
INSERT INTO elem_voc VALUES ('220', 'fly', N'飛、飛行', N'動詞');
INSERT INTO elem_voc VALUES ('221', 'food', N'食物', N'名詞');
INSERT INTO elem_voc VALUES ('222', 'foot', N'腳', N'名詞');
INSERT INTO elem_voc VALUES ('223', 'football', N'足球 (UK; 英式英語)', N'名詞');
INSERT INTO elem_voc VALUES ('224', 'for', N'給、為了(某人、物)', N'介系詞');
INSERT INTO elem_voc VALUES ('225', 'fork', N'叉子', N'名詞');
INSERT INTO elem_voc VALUES ('226', 'forty', N'四十', N'數字');
INSERT INTO elem_voc VALUES ('227', 'four', N'四', N'數字');
INSERT INTO elem_voc VALUES ('228', 'fourteen', N'十四', N'數字');
INSERT INTO elem_voc VALUES ('229', 'free', N'免費的', N'形容詞');
INSERT INTO elem_voc VALUES ('230', 'French fries', N'薯條', N'名詞');
INSERT INTO elem_voc VALUES ('231', 'Friday', N'星期五', N'名詞');
INSERT INTO elem_voc VALUES ('232', 'fridge', N'電冰箱 (= refrigerator)', N'名詞');
INSERT INTO elem_voc VALUES ('233', 'friend', N'朋友', N'名詞');
INSERT INTO elem_voc VALUES ('234', 'frog', N'青蛙', N'名詞');
INSERT INTO elem_voc VALUES ('235', 'from', N'從(某處)/(某時刻)/(某人)', N'介系詞');
INSERT INTO elem_voc VALUES ('236', 'fruit', N'水果', N'名詞');
INSERT INTO elem_voc VALUES ('237', 'full', N'飽的', N'形容詞');
INSERT INTO elem_voc VALUES ('238', 'fun', N'有趣的', N'形容詞');
INSERT INTO elem_voc VALUES ('239', 'fun', N'樂趣', N'名詞');
INSERT INTO elem_voc VALUES ('240', 'game', N'遊戲、比賽', N'名詞');
INSERT INTO elem_voc VALUES ('241', 'garden', N'院子、花園', N'名詞');
INSERT INTO elem_voc VALUES ('242', 'get', N'得到、收到', N'動詞');
INSERT INTO elem_voc VALUES ('243', 'gift', N'禮物', N'名詞');
INSERT INTO elem_voc VALUES ('244', 'girl', N'女孩', N'名詞');
INSERT INTO elem_voc VALUES ('245', 'give', N'給', N'動詞');
INSERT INTO elem_voc VALUES ('246', 'glass', N'玻璃杯', N'名詞');
INSERT INTO elem_voc VALUES ('247', 'glasses', N'眼鏡', N'名詞');
INSERT INTO elem_voc VALUES ('248', 'glue', N'膠水', N'名詞');
INSERT INTO elem_voc VALUES ('249', 'go', N'去、走', N'動詞');
INSERT INTO elem_voc VALUES ('250', 'good', N'好的', N'形容詞');
INSERT INTO elem_voc VALUES ('251', 'goodbye', N'再見 (= bye)', N'感嘆詞');
INSERT INTO elem_voc VALUES ('252', 'grandfather', N'外公、爺爺 (= grandpa)', N'名詞');
INSERT INTO elem_voc VALUES ('253', 'grandma', N'外婆、奶奶 (= grandmother)', N'名詞');
INSERT INTO elem_voc VALUES ('254', 'grandmother', N'外婆、奶奶 (= grandma)', N'名詞');
INSERT INTO elem_voc VALUES ('255', 'grandpa', N'外公、爺爺 (= grandfather)', N'名詞');
INSERT INTO elem_voc VALUES ('256', 'grape', N'葡萄', N'名詞');
INSERT INTO elem_voc VALUES ('257', 'gray', N'灰色的', N'形容詞');
INSERT INTO elem_voc VALUES ('258', 'great', N'很棒的', N'形容詞');
INSERT INTO elem_voc VALUES ('259', 'green', N'綠色的', N'形容詞');
INSERT INTO elem_voc VALUES ('260', 'grow', N'成長、長大', N'動詞');
INSERT INTO elem_voc VALUES ('261', 'hair', N'頭髮', N'名詞');
INSERT INTO elem_voc VALUES ('262', 'hamburger', N'漢堡', N'名詞');
INSERT INTO elem_voc VALUES ('263', 'hand', N'手', N'名詞');
INSERT INTO elem_voc VALUES ('264', 'happy', N'開心的、高興的', N'形容詞');
INSERT INTO elem_voc VALUES ('265', 'hard', N'困難的', N'形容詞');
INSERT INTO elem_voc VALUES ('266', 'hat', N'帽子', N'名詞');
INSERT INTO elem_voc VALUES ('267', 'have', N'助動詞', N'助動詞');
INSERT INTO elem_voc VALUES ('268', 'have', N'有', N'動詞');
INSERT INTO elem_voc VALUES ('269', 'he', N'他', N'代名詞');
INSERT INTO elem_voc VALUES ('270', 'head', N'頭', N'名詞');
INSERT INTO elem_voc VALUES ('271', 'headache', N'頭痛', N'名詞');
INSERT INTO elem_voc VALUES ('272', 'heavy', N'重的 (人)', N'形容詞');
INSERT INTO elem_voc VALUES ('273', 'heavy', N'重的 (物品)', N'形容詞');
INSERT INTO elem_voc VALUES ('274', 'hello', N'哈囉', N'感嘆詞');
INSERT INTO elem_voc VALUES ('275', 'help', N'幫助', N'動詞');
INSERT INTO elem_voc VALUES ('276', 'her', N'她的', N'限定詞');
INSERT INTO elem_voc VALUES ('277', 'her', N'她', N'代名詞');
INSERT INTO elem_voc VALUES ('278', 'here', N'這裡', N'副詞');
INSERT INTO elem_voc VALUES ('279', 'hi', N'嗨', N'感嘆詞');
INSERT INTO elem_voc VALUES ('280', 'high', N'高的', N'形容詞');
INSERT INTO elem_voc VALUES ('281', 'hike', N'健行', N'動詞');
INSERT INTO elem_voc VALUES ('282', 'him', N'他(受詞)', N'代名詞');
INSERT INTO elem_voc VALUES ('283', 'hippo', N'河馬', N'名詞');
INSERT INTO elem_voc VALUES ('284', 'his', N'他的', N'限定詞');
INSERT INTO elem_voc VALUES ('285', 'hit', N'打、碰撞', N'動詞');
INSERT INTO elem_voc VALUES ('286', 'home', N'家庭', N'名詞');
INSERT INTO elem_voc VALUES ('287', 'homework', N'回家作業', N'名詞');
INSERT INTO elem_voc VALUES ('288', 'hope', N'希望', N'動詞');
INSERT INTO elem_voc VALUES ('289', 'horse', N'馬', N'名詞');
INSERT INTO elem_voc VALUES ('290', 'hospital', N'醫院', N'名詞');
INSERT INTO elem_voc VALUES ('291', 'hot', N'熱的', N'形容詞');
INSERT INTO elem_voc VALUES ('292', 'hot', N'燙的', N'形容詞');
INSERT INTO elem_voc VALUES ('293', 'house', N'房子', N'名詞');
INSERT INTO elem_voc VALUES ('294', 'how', N'如何...', N'副詞');
INSERT INTO elem_voc VALUES ('295', 'hundred', N'一百', N'數字');
INSERT INTO elem_voc VALUES ('296', 'hungry', N'餓的', N'形容詞');
INSERT INTO elem_voc VALUES ('297', 'hurry', N'趕快、急忙', N'動詞');
INSERT INTO elem_voc VALUES ('298', 'hurt', N'受傷', N'動詞');
INSERT INTO elem_voc VALUES ('299', 'I', N'我', N'代名詞');
INSERT INTO elem_voc VALUES ('300', 'ice cream', N'冰淇淋', N'名詞');
INSERT INTO elem_voc VALUES ('301', 'in', N'在...裡面、在某短時間裡', N'介系詞');
INSERT INTO elem_voc VALUES ('302', 'in front of', N'在...前面', N'介系詞');
INSERT INTO elem_voc VALUES ('303', 'inside', N'在...裡面、向...裡面', N'介系詞');
INSERT INTO elem_voc VALUES ('304', 'interesting', N'有趣的', N'形容詞');
INSERT INTO elem_voc VALUES ('305', 'it', N'它、牠', N'代名詞');
INSERT INTO elem_voc VALUES ('306', 'its', N'它的、牠的', N'限定詞');
INSERT INTO elem_voc VALUES ('307', 'jacket', N'夾克、外套', N'名詞');
INSERT INTO elem_voc VALUES ('308', 'January', N'一月', N'名詞');
INSERT INTO elem_voc VALUES ('309', 'job', N'工作、職業', N'名詞');
INSERT INTO elem_voc VALUES ('310', 'juice', N'果汁', N'名詞');
INSERT INTO elem_voc VALUES ('311', 'July', N'七月', N'名詞');
INSERT INTO elem_voc VALUES ('312', 'jump', N'跳', N'動詞');
INSERT INTO elem_voc VALUES ('313', 'June', N'六月', N'名詞');
INSERT INTO elem_voc VALUES ('314', 'lake', N'湖', N'名詞');
INSERT INTO elem_voc VALUES ('315', 'lamp', N'燈', N'名詞');
INSERT INTO elem_voc VALUES ('316', 'last', N'最後的', N'限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('317', 'late', N'晚到（的）', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('318', 'laugh', N'笑', N'動詞');
INSERT INTO elem_voc VALUES ('319', 'lazy', N'懶惰的', N'形容詞');
INSERT INTO elem_voc VALUES ('320', 'left', N'左邊(的)', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('321', 'leg', N'腿', N'名詞');
INSERT INTO elem_voc VALUES ('322', 'lemon', N'檸檬', N'名詞');
INSERT INTO elem_voc VALUES ('323', 's', N'讓我們...', N'動詞');
INSERT INTO elem_voc VALUES ('324', 'library', N'圖書館', N'名詞');
INSERT INTO elem_voc VALUES ('325', 'light', N'輕的', N'形容詞');
INSERT INTO elem_voc VALUES ('326', 'like', N'喜歡', N'動詞');
INSERT INTO elem_voc VALUES ('327', 'lion', N'獅子', N'名詞');
INSERT INTO elem_voc VALUES ('328', 'listen', N'聽', N'動詞');
INSERT INTO elem_voc VALUES ('329', 'live', N'住', N'動詞');
INSERT INTO elem_voc VALUES ('330', 'living room', N'客廳', N'名詞');
INSERT INTO elem_voc VALUES ('331', 'long', N'長的', N'形容詞');
INSERT INTO elem_voc VALUES ('332', 'look', N'看、看起來', N'動詞');
INSERT INTO elem_voc VALUES ('333', 'love', N'愛、喜愛', N'動詞');
INSERT INTO elem_voc VALUES ('334', 'lunch', N'午餐', N'名詞');
INSERT INTO elem_voc VALUES ('335', 'lake', N'湖', N'名詞');
INSERT INTO elem_voc VALUES ('336', 'lamp', N'燈', N'名詞');
INSERT INTO elem_voc VALUES ('337', 'last', N'最後的', N'限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('338', 'late', N'晚到（的）', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('339', 'laugh', N'笑', N'動詞');
INSERT INTO elem_voc VALUES ('340', 'lazy', N'懶惰的', N'形容詞');
INSERT INTO elem_voc VALUES ('341', 'left', N'左邊(的)', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('342', 'leg', N'腿', N'名詞');
INSERT INTO elem_voc VALUES ('343', 'lemon', N'檸檬', N'名詞');
INSERT INTO elem_voc VALUES ('344', 'let''s', N'讓我們...', N'動詞');
INSERT INTO elem_voc VALUES ('345', 'library', N'圖書館', N'名詞');
INSERT INTO elem_voc VALUES ('346', 'light', N'輕的', N'形容詞');
INSERT INTO elem_voc VALUES ('347', 'like', N'喜歡', N'動詞');
INSERT INTO elem_voc VALUES ('348', 'lion', N'獅子', N'名詞');
INSERT INTO elem_voc VALUES ('349', 'listen', N'聽', N'動詞');
INSERT INTO elem_voc VALUES ('350', 'live', N'住', N'動詞');
INSERT INTO elem_voc VALUES ('351', 'living room', N'客廳', N'名詞');
INSERT INTO elem_voc VALUES ('352', 'long', N'長的', N'形容詞');
INSERT INTO elem_voc VALUES ('353', 'look', N'看、看起來', N'動詞');
INSERT INTO elem_voc VALUES ('354', 'love', N'愛、喜愛', N'動詞');
INSERT INTO elem_voc VALUES ('355', 'lunch', N'午餐', N'名詞');
INSERT INTO elem_voc VALUES ('356', 'mad', N'生氣的、氣憤的', N'形容詞');
INSERT INTO elem_voc VALUES ('357', 'mail', N'信', N'名詞');
INSERT INTO elem_voc VALUES ('358', 'mailman', N'郵差', N'名詞');
INSERT INTO elem_voc VALUES ('359', 'make', N'做、製造', N'動詞');
INSERT INTO elem_voc VALUES ('360', 'man', N'男人', N'名詞');
INSERT INTO elem_voc VALUES ('361', 'many', N'許多(例如many flowers)', N'限定詞, 形容詞');
INSERT INTO elem_voc VALUES ('362', 'March', N'三月', N'名詞');
INSERT INTO elem_voc VALUES ('363', 'marker', N'麥克筆', N'名詞');
INSERT INTO elem_voc VALUES ('364', 'market', N'市場', N'名詞');
INSERT INTO elem_voc VALUES ('365', 'math', N'數學', N'名詞');
INSERT INTO elem_voc VALUES ('366', 'May', N'五月', N'名詞');
INSERT INTO elem_voc VALUES ('367', 'maybe', N'也許', N'副詞');
INSERT INTO elem_voc VALUES ('368', 'me', N'我(受詞)', N'代名詞');
INSERT INTO elem_voc VALUES ('369', 'meal', N'餐', N'名詞');
INSERT INTO elem_voc VALUES ('370', 'meet', N'遇見、會面', N'動詞');
INSERT INTO elem_voc VALUES ('371', 'men', N'男人 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('372', 'mice', N'老鼠 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('373', 'milk', N'牛奶', N'名詞');
INSERT INTO elem_voc VALUES ('374', 'miss', N'想念', N'動詞');
INSERT INTO elem_voc VALUES ('375', 'Miss', N'小姐', N'');
INSERT INTO elem_voc VALUES ('376', 'mom', N'媽媽 (= mother; mommy)', N'名詞');
INSERT INTO elem_voc VALUES ('377', 'mommy', N'媽媽 (= mother; mom)', N'名詞');
INSERT INTO elem_voc VALUES ('378', 'Monday', N'星期一', N'名詞');
INSERT INTO elem_voc VALUES ('379', 'money', N'錢', N'名詞');
INSERT INTO elem_voc VALUES ('380', 'monkey', N'猴子', N'名詞');
INSERT INTO elem_voc VALUES ('381', 'month', N'月', N'名詞');
INSERT INTO elem_voc VALUES ('382', 'moon', N'月亮', N'名詞');
INSERT INTO elem_voc VALUES ('383', 'mop', N'用拖把拖地', N'動詞');
INSERT INTO elem_voc VALUES ('384', 'more', N'更多、較多', N'限定詞, 副詞');
INSERT INTO elem_voc VALUES ('385', 'morning', N'早上', N'名詞');
INSERT INTO elem_voc VALUES ('386', 'mother', N'媽媽 (= mom; mommy)', N'名詞');
INSERT INTO elem_voc VALUES ('387', 'motorcycle', N'摩托車', N'名詞');
INSERT INTO elem_voc VALUES ('388', 'mountain', N'山', N'名詞');
INSERT INTO elem_voc VALUES ('389', 'mouse', N'老鼠', N'名詞');
INSERT INTO elem_voc VALUES ('390', 'mouth', N'嘴巴', N'名詞');
INSERT INTO elem_voc VALUES ('391', 'movie', N'電影', N'名詞');
INSERT INTO elem_voc VALUES ('392', 'movie theater', N'電影院', N'名詞');
INSERT INTO elem_voc VALUES ('393', 'Mr.', N'先生', N'');
INSERT INTO elem_voc VALUES ('394', 'Mrs.', N'太太', N'');
INSERT INTO elem_voc VALUES ('395', 'MRT', N'捷運', N'名詞');
INSERT INTO elem_voc VALUES ('396', 'much', N'許多(例如much water)', N'限定詞,副詞');
INSERT INTO elem_voc VALUES ('397', 'museum', N'博物館', N'名詞');
INSERT INTO elem_voc VALUES ('398', 'music', N'音樂', N'名詞');
INSERT INTO elem_voc VALUES ('399', 'my', N'我的', N'限定詞');
INSERT INTO elem_voc VALUES ('400', 'name', N'名字', N'名詞');
INSERT INTO elem_voc VALUES ('401', 'near', N'靠近、接近', N'介系詞');
INSERT INTO elem_voc VALUES ('402', 'need', N'需要', N'動詞');
INSERT INTO elem_voc VALUES ('403', 'never', N'不曾', N'副詞');
INSERT INTO elem_voc VALUES ('404', 'new', N'新的', N'形容詞');
INSERT INTO elem_voc VALUES ('405', 'next to', N'在...旁邊', N'介系詞');
INSERT INTO elem_voc VALUES ('406', 'nice', N'令人愉快的、宜人的', N'形容詞');
INSERT INTO elem_voc VALUES ('407', 'night', N'晚上', N'名詞');
INSERT INTO elem_voc VALUES ('408', 'nine', N'九', N'數字');
INSERT INTO elem_voc VALUES ('409', 'nineteen', N'十九', N'數字');
INSERT INTO elem_voc VALUES ('410', 'ninety', N'九十', N'數字');
INSERT INTO elem_voc VALUES ('411', 'no', N'不', N'副詞');
INSERT INTO elem_voc VALUES ('412', 'noodles', N'麵', N'名詞');
INSERT INTO elem_voc VALUES ('413', 'nose', N'鼻子', N'名詞');
INSERT INTO elem_voc VALUES ('414', 'not', N'不、沒有', N'副詞');
INSERT INTO elem_voc VALUES ('415', 'nothing', N'什麼都沒有', N'代名詞');
INSERT INTO elem_voc VALUES ('416', 'November', N'十一月', N'名詞');
INSERT INTO elem_voc VALUES ('417', 'now', N'現在', N'副詞');
INSERT INTO elem_voc VALUES ('418', 'number', N'數字', N'名詞');
INSERT INTO elem_voc VALUES ('419', 'nurse', N'護士', N'名詞');
INSERT INTO elem_voc VALUES ('420', 'clock', N'...點鐘', N'副詞');
INSERT INTO elem_voc VALUES ('421', 'October', N'十月', N'名詞');
INSERT INTO elem_voc VALUES ('422', 'of', N'...的', N'介系詞');
INSERT INTO elem_voc VALUES ('423', 'off', N'離開、從...去掉', N'介系詞');
INSERT INTO elem_voc VALUES ('424', 'office', N'辦公室', N'名詞');
INSERT INTO elem_voc VALUES ('425', 'OK', N'好的', N'形容詞');
INSERT INTO elem_voc VALUES ('426', 'OK', N'沒事', N'副詞');
INSERT INTO elem_voc VALUES ('427', 'old', N'1. 年紀、年齡；2. 老的', N'形容詞');
INSERT INTO elem_voc VALUES ('428', 'on', N'在...上面；在(某一天)', N'介系詞');
INSERT INTO elem_voc VALUES ('429', 'one', N'一', N'數字');
INSERT INTO elem_voc VALUES ('430', 'only', N'僅有的', N'形容詞');
INSERT INTO elem_voc VALUES ('431', 'only', N'唯一地', N'副詞');
INSERT INTO elem_voc VALUES ('432', 'open', N'開', N'動詞');
INSERT INTO elem_voc VALUES ('433', 'orange', N'橘色的', N'形容詞');
INSERT INTO elem_voc VALUES ('434', 'orange', N'橘子', N'名詞');
INSERT INTO elem_voc VALUES ('435', 'other', N'其他的', N'形容詞, 代名詞, 限定詞');
INSERT INTO elem_voc VALUES ('436', 'our', N'我們的', N'限定詞');
INSERT INTO elem_voc VALUES ('437', 'out', N'向外地', N'介系詞');
INSERT INTO elem_voc VALUES ('438', 'outside', N'在...外面、向...外面', N'介系詞');
INSERT INTO elem_voc VALUES ('439', 'over', N'在...上方', N'介系詞');
INSERT INTO elem_voc VALUES ('440', 'paint', N'用顏料畫、刷油漆', N'動詞');
INSERT INTO elem_voc VALUES ('441', 'pair', N'一雙、一對', N'名詞');
INSERT INTO elem_voc VALUES ('442', 'panda', N'大貓熊', N'名詞');
INSERT INTO elem_voc VALUES ('443', 'pants', N'長褲', N'名詞');
INSERT INTO elem_voc VALUES ('444', 'paper', N'紙張', N'名詞');
INSERT INTO elem_voc VALUES ('445', 'parent', N'父母親', N'名詞');
INSERT INTO elem_voc VALUES ('446', 'park', N'公園', N'名詞');
INSERT INTO elem_voc VALUES ('447', 'party', N'派對', N'名詞');
INSERT INTO elem_voc VALUES ('448', 'PE', N'體育（課）', N'名詞');
INSERT INTO elem_voc VALUES ('449', 'peach', N'桃子', N'名詞');
INSERT INTO elem_voc VALUES ('450', 'pen', N'筆、鋼筆', N'名詞');
INSERT INTO elem_voc VALUES ('451', 'pencil', N'鉛筆', N'名詞');
INSERT INTO elem_voc VALUES ('452', 'people', N'人 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('453', 'person', N'人', N'名詞');
INSERT INTO elem_voc VALUES ('454', 'pet', N'寵物', N'名詞');
INSERT INTO elem_voc VALUES ('455', 'photo', N'照片', N'名詞');
INSERT INTO elem_voc VALUES ('456', 'piano', N'鋼琴', N'名詞');
INSERT INTO elem_voc VALUES ('457', 'pick up', N'撿起、接（人）、接（電話）', N'動詞');
INSERT INTO elem_voc VALUES ('458', 'picture', N'圖片、照片', N'名詞');
INSERT INTO elem_voc VALUES ('459', 'pie', N'派', N'名詞');
INSERT INTO elem_voc VALUES ('460', 'pig', N'豬', N'名詞');
INSERT INTO elem_voc VALUES ('461', 'pink', N'粉紅色的', N'形容詞');
INSERT INTO elem_voc VALUES ('462', 'pizza', N'披薩', N'名詞');
INSERT INTO elem_voc VALUES ('463', 'plane', N'飛機 (= airplane)', N'名詞');
INSERT INTO elem_voc VALUES ('464', 'play', N'玩', N'動詞');
INSERT INTO elem_voc VALUES ('465', 'please', N'請', N'感嘆詞');
INSERT INTO elem_voc VALUES ('466', 'pocket', N'口袋', N'名詞');
INSERT INTO elem_voc VALUES ('467', 'police officer', N'警察', N'名詞');
INSERT INTO elem_voc VALUES ('468', 'police station', N'警察局', N'名詞');
INSERT INTO elem_voc VALUES ('469', 'pork', N'豬肉', N'名詞');
INSERT INTO elem_voc VALUES ('470', 'post office', N'郵局', N'名詞');
INSERT INTO elem_voc VALUES ('471', 'pretty', N'漂亮的', N'形容詞');
INSERT INTO elem_voc VALUES ('472', 'pumpkin', N'南瓜', N'名詞');
INSERT INTO elem_voc VALUES ('473', 'purple', N'紫色的', N'形容詞');
INSERT INTO elem_voc VALUES ('474', 'put', N'放', N'動詞');
INSERT INTO elem_voc VALUES ('475', 'question', N'問題', N'名詞');
INSERT INTO elem_voc VALUES ('476', 'quiet', N'安靜的', N'形容詞');
INSERT INTO elem_voc VALUES ('477', 'rabbit', N'兔子', N'名詞');
INSERT INTO elem_voc VALUES ('478', 'rain', N'雨水', N'名詞');
INSERT INTO elem_voc VALUES ('479', 'rain', N'下雨', N'動詞');
INSERT INTO elem_voc VALUES ('480', 'rainbow', N'彩虹', N'名詞');
INSERT INTO elem_voc VALUES ('481', 'rainy', N'下雨的/多雨的', N'形容詞');
INSERT INTO elem_voc VALUES ('482', 'read', N'閱讀', N'動詞');
INSERT INTO elem_voc VALUES ('483', 'ready', N'準備好的', N'形容詞');
INSERT INTO elem_voc VALUES ('484', 'really', N'真正地', N'副詞');
INSERT INTO elem_voc VALUES ('485', 'red', N'紅色的', N'形容詞');
INSERT INTO elem_voc VALUES ('486', 'refrigerator', N'電冰箱 (= fridge)', N'名詞');
INSERT INTO elem_voc VALUES ('487', 'restaurant', N'餐廳', N'名詞');
INSERT INTO elem_voc VALUES ('488', 'restroom', N'洗手間、廁所', N'名詞');
INSERT INTO elem_voc VALUES ('489', 'rice', N'米飯', N'名詞');
INSERT INTO elem_voc VALUES ('490', 'ride', N'騎（機車、腳踏車等）', N'動詞');
INSERT INTO elem_voc VALUES ('491', 'right', N'對的', N'形容詞');
INSERT INTO elem_voc VALUES ('492', 'right', N'右邊', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('493', 'river', N'河流', N'名詞');
INSERT INTO elem_voc VALUES ('494', 'robot', N'機器人', N'名詞');
INSERT INTO elem_voc VALUES ('495', 'ruler', N'尺', N'名詞');
INSERT INTO elem_voc VALUES ('496', 'run', N'跑、跑步', N'動詞');
INSERT INTO elem_voc VALUES ('497', 'table', N'桌子', N'名詞');
INSERT INTO elem_voc VALUES ('498', 'take', N'攜帶、拿取', N'動詞');
INSERT INTO elem_voc VALUES ('499', 'talk', N'說話、談話', N'動詞');
INSERT INTO elem_voc VALUES ('500', 'tall', N'高的', N'形容詞');
INSERT INTO elem_voc VALUES ('501', 'taste', N'嚐起來', N'動詞');
INSERT INTO elem_voc VALUES ('502', 'taxi', N'計程車', N'名詞');
INSERT INTO elem_voc VALUES ('503', 'tea', N'茶', N'名詞');
INSERT INTO elem_voc VALUES ('504', 'teacher', N'老師', N'名詞');
INSERT INTO elem_voc VALUES ('505', 'teeth', N'牙齒 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('506', 'telephone', N'電話', N'名詞');
INSERT INTO elem_voc VALUES ('507', 'television', N'電視 (= TV)', N'名詞');
INSERT INTO elem_voc VALUES ('508', 'tell', N'告訴、告知', N'動詞');
INSERT INTO elem_voc VALUES ('509', 'ten', N'十', N'數字');
INSERT INTO elem_voc VALUES ('510', 'test', N'考試', N'名詞');
INSERT INTO elem_voc VALUES ('511', 'than', N'比', N'介系詞');
INSERT INTO elem_voc VALUES ('512', 'thank', N'感謝（某人）', N'動詞');
INSERT INTO elem_voc VALUES ('513', 'that', N'那個', N'限定詞');
INSERT INTO elem_voc VALUES ('514', 'the', N'這', N'冠詞');
INSERT INTO elem_voc VALUES ('515', 'their', N'他們的', N'限定詞');
INSERT INTO elem_voc VALUES ('516', 'them', N'他們(受詞)', N'代名詞');
INSERT INTO elem_voc VALUES ('517', 'then', N'然後、接著', N'副詞');
INSERT INTO elem_voc VALUES ('518', 'there', N'那裡', N'副詞');
INSERT INTO elem_voc VALUES ('519', 'these', N'這些', N'限定詞');
INSERT INTO elem_voc VALUES ('520', 'they', N'他們', N'代名詞');
INSERT INTO elem_voc VALUES ('521', 'thin', N'瘦的', N'形容詞');
INSERT INTO elem_voc VALUES ('522', 'thing', N'東西、物', N'名詞');
INSERT INTO elem_voc VALUES ('523', 'third', N'第三', N'數字');
INSERT INTO elem_voc VALUES ('524', 'thirsty', N'口渴的', N'形容詞');
INSERT INTO elem_voc VALUES ('525', 'thirteen', N'十三', N'數字');
INSERT INTO elem_voc VALUES ('526', 'thirty', N'三十', N'數字');
INSERT INTO elem_voc VALUES ('527', 'this', N'這個', N'限定詞');
INSERT INTO elem_voc VALUES ('528', 'those', N'那些', N'限定詞');
INSERT INTO elem_voc VALUES ('529', 'three', N'三', N'數字');
INSERT INTO elem_voc VALUES ('530', 'Thursday', N'星期四', N'名詞');
INSERT INTO elem_voc VALUES ('531', 'ticket', N'票', N'名詞');
INSERT INTO elem_voc VALUES ('532', 'tiger', N'老虎', N'名詞');
INSERT INTO elem_voc VALUES ('533', 'time', N'時間', N'名詞');
INSERT INTO elem_voc VALUES ('534', 'tired', N'疲累的', N'形容詞');
INSERT INTO elem_voc VALUES ('535', 'to', N'向、朝、對著', N'介系詞');
INSERT INTO elem_voc VALUES ('536', 'today', N'今天', N'名詞');
INSERT INTO elem_voc VALUES ('537', 'together', N'一起', N'副詞');
INSERT INTO elem_voc VALUES ('538', 'tomorrow', N'明天', N'名詞');
INSERT INTO elem_voc VALUES ('539', 'too', N'1. 也；2. 太...', N'副詞');
INSERT INTO elem_voc VALUES ('540', 'tooth', N'牙齒', N'名詞');
INSERT INTO elem_voc VALUES ('541', 'toothache', N'牙痛', N'名詞');
INSERT INTO elem_voc VALUES ('542', 'touch', N'觸碰', N'動詞');
INSERT INTO elem_voc VALUES ('543', 'towel', N'毛巾', N'名詞');
INSERT INTO elem_voc VALUES ('544', 'toy', N'玩具', N'名詞');
INSERT INTO elem_voc VALUES ('545', 'train', N'火車', N'名詞');
INSERT INTO elem_voc VALUES ('546', 'trash', N'垃圾', N'名詞');
INSERT INTO elem_voc VALUES ('547', 'tree', N'樹', N'名詞');
INSERT INTO elem_voc VALUES ('548', 'trip', N'（短程的）旅行', N'名詞');
INSERT INTO elem_voc VALUES ('549', 'truck', N'卡車', N'名詞');
INSERT INTO elem_voc VALUES ('550', 'try', N'嘗試', N'動詞');
INSERT INTO elem_voc VALUES ('551', 'T-shirt', N'T 恤', N'名詞');
INSERT INTO elem_voc VALUES ('552', 'Tuesday', N'星期二', N'名詞');
INSERT INTO elem_voc VALUES ('553', 'turn', N'轉彎', N'動詞');
INSERT INTO elem_voc VALUES ('554', 'turtle', N'烏龜', N'名詞');
INSERT INTO elem_voc VALUES ('555', 'TV', N'電視 (= television)', N'名詞');
INSERT INTO elem_voc VALUES ('556', 'twelve', N'十二', N'數字');
INSERT INTO elem_voc VALUES ('557', 'twenty', N'二十', N'數字');
INSERT INTO elem_voc VALUES ('558', 'two', N'二', N'數字');
INSERT INTO elem_voc VALUES ('559', 'typhoon', N'颱風', N'名詞');
INSERT INTO elem_voc VALUES ('560', 'table', N'桌子', N'名詞');
INSERT INTO elem_voc VALUES ('561', 'take', N'攜帶、拿取', N'動詞');
INSERT INTO elem_voc VALUES ('562', 'talk', N'說話、談話', N'動詞');
INSERT INTO elem_voc VALUES ('563', 'tall', N'高的', N'形容詞');
INSERT INTO elem_voc VALUES ('564', 'taste', N'嚐起來', N'動詞');
INSERT INTO elem_voc VALUES ('565', 'taxi', N'計程車', N'名詞');
INSERT INTO elem_voc VALUES ('566', 'tea', N'茶', N'名詞');
INSERT INTO elem_voc VALUES ('567', 'teacher', N'老師', N'名詞');
INSERT INTO elem_voc VALUES ('568', 'teeth', N'牙齒 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('569', 'telephone', N'電話', N'名詞');
INSERT INTO elem_voc VALUES ('570', 'television', N'電視 (= TV)', N'名詞');
INSERT INTO elem_voc VALUES ('571', 'tell', N'告訴、告知', N'動詞');
INSERT INTO elem_voc VALUES ('572', 'ten', N'十', N'數字');
INSERT INTO elem_voc VALUES ('573', 'test', N'考試', N'名詞');
INSERT INTO elem_voc VALUES ('574', 'than', N'比', N'介系詞');
INSERT INTO elem_voc VALUES ('575', 'thank', N'感謝（某人）', N'動詞');
INSERT INTO elem_voc VALUES ('576', 'that', N'那個', N'限定詞');
INSERT INTO elem_voc VALUES ('577', 'the', N'這', N'冠詞');
INSERT INTO elem_voc VALUES ('578', 'their', N'他們的', N'限定詞');
INSERT INTO elem_voc VALUES ('579', 'them', N'他們(受詞)', N'代名詞');
INSERT INTO elem_voc VALUES ('580', 'then', N'然後、接著', N'副詞');
INSERT INTO elem_voc VALUES ('581', 'there', N'那裡', N'副詞');
INSERT INTO elem_voc VALUES ('582', 'these', N'這些', N'限定詞');
INSERT INTO elem_voc VALUES ('583', 'they', N'他們', N'代名詞');
INSERT INTO elem_voc VALUES ('584', 'thin', N'瘦的', N'形容詞');
INSERT INTO elem_voc VALUES ('585', 'thing', N'東西、物', N'名詞');
INSERT INTO elem_voc VALUES ('586', 'third', N'第三', N'數字');
INSERT INTO elem_voc VALUES ('587', 'thirsty', N'口渴的', N'形容詞');
INSERT INTO elem_voc VALUES ('588', 'thirteen', N'十三', N'數字');
INSERT INTO elem_voc VALUES ('589', 'thirty', N'三十', N'數字');
INSERT INTO elem_voc VALUES ('590', 'this', N'這個', N'限定詞');
INSERT INTO elem_voc VALUES ('591', 'those', N'那些', N'限定詞');
INSERT INTO elem_voc VALUES ('592', 'three', N'三', N'數字');
INSERT INTO elem_voc VALUES ('593', 'Thursday', N'星期四', N'名詞');
INSERT INTO elem_voc VALUES ('594', 'ticket', N'票', N'名詞');
INSERT INTO elem_voc VALUES ('595', 'tiger', N'老虎', N'名詞');
INSERT INTO elem_voc VALUES ('596', 'time', N'時間', N'名詞');
INSERT INTO elem_voc VALUES ('597', 'tired', N'疲累的', N'形容詞');
INSERT INTO elem_voc VALUES ('598', 'to', N'向、朝、對著', N'介系詞');
INSERT INTO elem_voc VALUES ('599', 'today', N'今天', N'名詞');
INSERT INTO elem_voc VALUES ('600', 'together', N'一起', N'副詞');
INSERT INTO elem_voc VALUES ('601', 'tomorrow', N'明天', N'名詞');
INSERT INTO elem_voc VALUES ('602', 'too', N'1. 也；2. 太...', N'副詞');
INSERT INTO elem_voc VALUES ('603', 'tooth', N'牙齒', N'名詞');
INSERT INTO elem_voc VALUES ('604', 'toothache', N'牙痛', N'名詞');
INSERT INTO elem_voc VALUES ('605', 'touch', N'觸碰', N'動詞');
INSERT INTO elem_voc VALUES ('606', 'towel', N'毛巾', N'名詞');
INSERT INTO elem_voc VALUES ('607', 'toy', N'玩具', N'名詞');
INSERT INTO elem_voc VALUES ('608', 'train', N'火車', N'名詞');
INSERT INTO elem_voc VALUES ('609', 'trash', N'垃圾', N'名詞');
INSERT INTO elem_voc VALUES ('610', 'tree', N'樹', N'名詞');
INSERT INTO elem_voc VALUES ('611', 'trip', N'（短程的）旅行', N'名詞');
INSERT INTO elem_voc VALUES ('612', 'truck', N'卡車', N'名詞');
INSERT INTO elem_voc VALUES ('613', 'try', N'嘗試', N'動詞');
INSERT INTO elem_voc VALUES ('614', 'T-shirt', N'T 恤', N'名詞');
INSERT INTO elem_voc VALUES ('615', 'Tuesday', N'星期二', N'名詞');
INSERT INTO elem_voc VALUES ('616', 'turn', N'轉彎', N'動詞');
INSERT INTO elem_voc VALUES ('617', 'turtle', N'烏龜', N'名詞');
INSERT INTO elem_voc VALUES ('618', 'TV', N'電視 (= television)', N'名詞');
INSERT INTO elem_voc VALUES ('619', 'twelve', N'十二', N'數字');
INSERT INTO elem_voc VALUES ('620', 'twenty', N'二十', N'數字');
INSERT INTO elem_voc VALUES ('621', 'two', N'二', N'數字');
INSERT INTO elem_voc VALUES ('622', 'typhoon', N'颱風', N'名詞');
INSERT INTO elem_voc VALUES ('623', 'umbrella', N'傘', N'名詞');
INSERT INTO elem_voc VALUES ('624', 'uncle', N'叔叔、舅舅、姑丈、姨丈', N'名詞');
INSERT INTO elem_voc VALUES ('625', 'under', N'在...下方', N'介系詞');
INSERT INTO elem_voc VALUES ('626', 'up', N'向上', N'介系詞');
INSERT INTO elem_voc VALUES ('627', 'us', N'我們(受詞)', N'代名詞');
INSERT INTO elem_voc VALUES ('628', 'usually', N'通常', N'副詞');
INSERT INTO elem_voc VALUES ('629', 'vacation', N'假期', N'名詞');
INSERT INTO elem_voc VALUES ('630', 'very', N'非常', N'副詞');
INSERT INTO elem_voc VALUES ('631', 'wait', N'等、等待', N'動詞');
INSERT INTO elem_voc VALUES ('632', 'waiter', N'男服務生', N'名詞');
INSERT INTO elem_voc VALUES ('633', 'waitress', N'女服務生', N'名詞');
INSERT INTO elem_voc VALUES ('634', 'wake', N'醒來、喚醒', N'動詞');
INSERT INTO elem_voc VALUES ('635', 'walk', N'走路', N'動詞');
INSERT INTO elem_voc VALUES ('636', 'wall', N'牆壁', N'名詞');
INSERT INTO elem_voc VALUES ('637', 'want', N'想要', N'動詞');
INSERT INTO elem_voc VALUES ('638', 'warm', N'溫暖的', N'形容詞');
INSERT INTO elem_voc VALUES ('639', 'wash', N'洗', N'動詞');
INSERT INTO elem_voc VALUES ('640', 'watch', N'手錶', N'名詞');
INSERT INTO elem_voc VALUES ('641', 'watch', N'看', N'動詞');
INSERT INTO elem_voc VALUES ('642', 'water', N'水', N'名詞');
INSERT INTO elem_voc VALUES ('643', 'watermelon', N'西瓜', N'名詞');
INSERT INTO elem_voc VALUES ('644', 'way', N'路、方向', N'名詞');
INSERT INTO elem_voc VALUES ('645', 'we', N'我們', N'代名詞');
INSERT INTO elem_voc VALUES ('646', 'wear', N'穿、戴', N'動詞');
INSERT INTO elem_voc VALUES ('647', 'weather', N'天氣', N'名詞');
INSERT INTO elem_voc VALUES ('648', 'Wednesday', N'星期三', N'名詞');
INSERT INTO elem_voc VALUES ('649', 'week', N'星期', N'名詞');
INSERT INTO elem_voc VALUES ('650', 'welcome', N'歡迎', N'動詞');
INSERT INTO elem_voc VALUES ('651', 'well', N'好的, 健康地', N'形容詞, 副詞');
INSERT INTO elem_voc VALUES ('652', 'wet', N'潮濕的', N'形容詞');
INSERT INTO elem_voc VALUES ('653', 'wet', N'濕的', N'形容詞');
INSERT INTO elem_voc VALUES ('654', 'whale', N'鯨魚', N'名詞');
INSERT INTO elem_voc VALUES ('655', 'what', N'什麼...', N'代名詞');
INSERT INTO elem_voc VALUES ('656', 'when', N'何時...', N'副詞');
INSERT INTO elem_voc VALUES ('657', 'where', N'在哪裡...', N'副詞');
INSERT INTO elem_voc VALUES ('658', 'which', N'哪一個...', N'限定詞');
INSERT INTO elem_voc VALUES ('659', 'white', N'白色的', N'形容詞');
INSERT INTO elem_voc VALUES ('660', 'who', N'誰...', N'代名詞');
INSERT INTO elem_voc VALUES ('661', 'whose', N'誰的...', N'限定詞');
INSERT INTO elem_voc VALUES ('662', 'why', N'為什麼...', N'副詞');
INSERT INTO elem_voc VALUES ('663', 'will', N'將會', N'助動詞');
INSERT INTO elem_voc VALUES ('664', 'win', N'贏', N'動詞');
INSERT INTO elem_voc VALUES ('665', 'wind', N'風', N'名詞');
INSERT INTO elem_voc VALUES ('666', 'window', N'窗戶', N'名詞');
INSERT INTO elem_voc VALUES ('667', 'windy', N'風大的', N'形容詞');
INSERT INTO elem_voc VALUES ('668', 'winter', N'冬天', N'名詞');
INSERT INTO elem_voc VALUES ('669', 'with', N'和...一起', N'介系詞');
INSERT INTO elem_voc VALUES ('670', 'woman', N'女人', N'名詞');
INSERT INTO elem_voc VALUES ('671', 'women', N'女人 (複數)', N'名詞');
INSERT INTO elem_voc VALUES ('672', 'wonderful', N'很棒的、精彩的', N'形容詞');
INSERT INTO elem_voc VALUES ('673', 'word', N'字', N'名詞');
INSERT INTO elem_voc VALUES ('674', 'work', N'工作', N'名詞');
INSERT INTO elem_voc VALUES ('675', 'worker', N'工作者', N'名詞');
INSERT INTO elem_voc VALUES ('676', 'worry', N'擔心', N'動詞');
INSERT INTO elem_voc VALUES ('677', 'write', N'寫', N'動詞');
INSERT INTO elem_voc VALUES ('679', 'year', N'年', N'名詞');
INSERT INTO elem_voc VALUES ('680', 'yellow', N'黃色的', N'形容詞');
INSERT INTO elem_voc VALUES ('681', 'yes', N'是', N'副詞');
INSERT INTO elem_voc VALUES ('682', 'yesterday', N'昨天', N'名詞');
INSERT INTO elem_voc VALUES ('683', 'you', N'你；你們', N'代名詞');
INSERT INTO elem_voc VALUES ('684', 'young', N'年輕的', N'形容詞');
INSERT INTO elem_voc VALUES ('685', 'your', N'你的、你們的', N'限定詞');
INSERT INTO elem_voc VALUES ('686', 'yummy', N'好吃的、美味的', N'形容詞');
